-- Generated by tools/build_forever.py from the WoW Forever game client's own
-- data tables (build 1.60.1.70338, via wago.tools). Do not edit.
local D = WaypointTrackerData
if not D then
    return
end
D.client = {
    build = "1.60.1.70338",
    -- quest markers: quest, start/end/objN, continent, zone, world x, world y
    pois = [[
91564	end	1	2482	5147.0	-1466.0
91564	start	1	2482	5147.0	-1466.0
92742	end	0	1436	-10636.0	1180.0
92742	obj0	0	1436	-9836.0	1035.0
92742	obj1	0	1436	-10290.0	1404.0
92742	start	0	1436	-10636.0	1180.0
92744	end	0	1436	-10636.0	1180.0
92744	obj0	0	1436	-9627.3	1472.5
92744	obj0	0	1436	-10641.8	2105.7
92744	obj0	0	1436	-10022.7	1887.6
92744	start	0	1436	-10636.0	1180.0
92745	end	0	1436	-10636.0	1180.0
92745	obj0	0	1436	-9863.4	1427.6
92745	obj1	0	1436	-10524.1	1974.7
92745	start	0	1436	-10636.0	1180.0
92747	end	0	1436	-10636.0	1180.0
92747	obj0	0	1436	-11010.8	1486.8
92747	start	0	1436	-10636.0	1180.0
92748	end	0	1453	-8350.0	648.0
92748	start	0	1436	-10636.0	1180.0
92749	end	0	1453	-8350.0	648.0
92749	start	0	1453	-8350.0	648.0
92750	end	0	1429	-8808.0	328.0
92750	start	0	1453	-8350.0	648.0
92751	end	0	1453	-8350.0	648.0
92751	start	0	1429	-8808.0	328.0
92752	end	0	1436	-10636.0	1180.0
92752	start	0	1453	-8350.0	648.0
92753	end	0	1436	-11353.0	1663.0
92753	start	0	1436	-10636.0	1180.0
92819	end	0	1436	-11353.0	1663.0
92819	start	0	1436	-11353.0	1663.0
96912	end	1	1446	-7127.0	-3800.0
96912	start	1	1446	-7127.0	-3800.0
96913	end	1	1446	-7127.0	-3800.0
96913	start	1	1446	-7127.0	-3800.0
96914	end	1	1446	-7127.0	-3800.0
96914	start	1	1446	-7127.0	-3800.0
96915	end	1	1446	-7127.0	-3800.0
96915	start	1	1446	-7127.0	-3800.0
96916	end	1	1446	-7127.0	-3800.0
96916	start	1	1446	-7127.0	-3800.0
96917	end	1	1446	-7127.0	-3800.0
96917	start	1	1446	-7127.0	-3800.0
96918	end	1	1446	-7127.0	-3800.0
96918	start	1	1446	-7127.0	-3800.0
96919	end	1	1446	-7127.0	-3800.0
96919	start	1	1446	-7127.0	-3800.0
96920	end	1	1446	-7127.0	-3800.0
96920	start	1	1446	-7127.0	-3800.0
96921	end	1	1446	-7127.0	-3800.0
96921	start	1	1446	-7127.0	-3800.0
]],
    -- flight paths: id, continent, zone, world x, world y, faction
    flights = [[
1	0	1453	-8889.0	-0.5	
2	0	1453	-8832.8	478.6	A
4	0	1436	-10628.9	1036.7	A
5	0	1433	-9429.1	-2231.4	A
6	0	1455	-4821.8	-1155.4	A
7	0	1437	-3792.3	-783.3	A
8	0	1432	-5421.9	-2930.0	A
9	0	1434	-14271.8	299.9	
10	0	1421	478.9	1536.6	H
11	0	1458	1568.6	268.0	H
12	0	1430	-10515.5	-1261.7	A
13	0	1416	-0.1	-859.9	H
14	0	1424	-711.5	-515.5	A
15	0	1423	2253.4	-5344.9	
16	0	1417	-1240.5	-2515.1	A
17	0	1417	-916.3	-3496.9	H
18	0	1434	-14444.3	509.6	H
19	0	1434	-14473.0	464.1	A
20	0	1434	-12414.2	146.3	H
21	0	1427	-6634.0	-2180.1	H
22	1	1456	-1197.2	29.7	H
23	1	1454	1677.6	-4315.7	H
24	0	1427	-6666.0	-2222.3	
25	1	1411	-441.8	-2596.1	H
26	1	1448	6341.4	557.7	A
27	1	1438	8643.6	841.0	A
28	1	1442	2827.3	-289.2	A
29	1	1442	966.6	1040.3	H
30	1	1441	-5407.7	-2414.3	H
31	1	1441	-4491.9	-775.9	A
32	1	1445	-3825.4	-4516.6	A
33	1	1442	2681.1	1461.7	A
34	1	1413	-1965.2	-5824.3	
35	1	1411	1320.1	-4649.2	
36	0	1453	-8644.6	433.3	
37	1	1443	139.2	1325.8	A
38	1	1443	-1767.6	3263.9	H
39	1	1446	-7224.0	-3734.6	A
40	1	1446	-7048.9	-3780.4	H
41	1	1444	-4373.8	3338.6	A
42	1	1444	-4419.9	199.3	H
43	0	1416	283.7	-2002.8	A
44	1	1447	3661.5	-4390.4	H
45	0	1435	-11112.2	-3435.7	A
46	0	1424	-986.4	-547.9	
47	0	1434	-12418.8	235.4	
48	1	1448	5068.4	-337.2	H
49	1	1450	7458.5	-2487.2	A
50	0	1416	0.0	0.0	
51	0	1416	0.0	0.0	
52	1	1452	6799.2	-4742.4	A
53	1	1452	6813.1	-4611.1	H
54	1	1444	-4203.9	3284.0	
55	1	1445	-3147.4	-2842.2	H
56	0	1435	-10457.0	-3279.2	H
57	1	1438	8701.5	991.4	
58	1	1448	3374.7	997.0	H
61	1	1440	2302.4	-2524.6	H
62	1	1450	7793.6	-2403.5	A
63	1	1450	7787.7	-2404.1	H
64	1	1447	2722.0	-3880.6	A
65	1	2482	6205.9	-1949.6	A
66	0	1416	931.3	-1430.1	A
67	0	1423	2271.1	-5340.8	A
68	0	1423	2327.4	-5286.9	H
69	1	1450	7470.4	-2123.4	H
70	0	1427	-7504.0	-2187.5	H
71	0	1428	-8364.6	-2738.4	A
72	1	1451	-6811.4	836.7	H
73	1	1451	-6761.8	772.0	A
74	0	1427	-6552.6	-1168.3	A
75	0	1427	-6554.9	-1100.1	H
76	0	1425	-635.3	-4720.5	H
77	1	1445	-2380.7	-1882.7	H
78	0	1422	3133.3	-3399.9	
79	1	1449	-6113.8	-1142.7	AH
80	1	1411	-894.6	-3773.0	AH
84	0	1422	2998.7	-3050.1	AH
85	0	1423	3109.3	-4285.1	AH
86	0	1423	2499.2	-4742.9	AH
87	0	1422	1857.6	-3658.5	AH
559	1	2482	5283.2	-3306.7	AH
3203	0	2548	-7923.7	-4783.0	H
3205	0	1426	-4375.7	864.8	
3242	1	2482	4393.5	-2836.4	AH
3274	0	2548	-8157.2	-5724.7	
3275	0	2548	-8180.0	-5616.3	
3276	0	2548	-9104.1	-4830.5	A
]],
    -- towns: id, continent, zone, world x, world y
    towns = [[
1	0	1426	-6134.3	383.8
2	0	1422	2249.9	278.4
3	0	1430	-10564.7	-1170.7
4	0	1420	1879.8	1588.2
5	0	1437	-4191.0	-2373.1
6	0	1437	-2610.3	-2350.6
7	0	1429	-9480.1	63.5
8	0	1455	-5021.0	-834.1
9	0	1426	-5586.0	-482.1
10	0	1433	-9227.7	-2201.5
11	0	1437	-3672.7	-828.5
12	0	1436	-11017.1	1510.2
13	0	1429	-8896.2	-179.3
14	0	1431	-10752.5	310.4
15	0	1436	-10503.7	1027.8
16	0	1453	-9153.8	364.1
17	0	1421	508.1	1619.0
18	0	1458	1849.7	235.7
19	0	1432	-5349.3	-2959.9
22	0	1424	-803.0	-531.7
23	0	1416	-27.0	-900.6
24	0	1417	-1251.1	-2526.8
25	0	1417	-991.6	-3528.3
26	0	1427	-6676.4	-2186.7
27	0	1418	-6392.6	-3158.0
28	1	1412	-2323.9	-395.0
29	1	1456	-1205.4	29.4
30	1	1412	-2906.5	-253.6
31	1	1411	312.7	-4745.5
32	1	1411	-604.1	-4202.9
33	1	1454	1381.8	-4371.2
34	1	1411	-819.5	-4918.2
35	1	1411	-455.9	-2652.1
36	1	1438	10462.7	806.0
37	1	1438	9788.0	949.9
38	1	1457	9951.8	2254.5
39	1	1411	-951.4	-3680.1
40	0	1434	-14383.3	487.1
41	0	1434	-12378.4	185.7
42	1	1442	2720.4	-382.4
44	1	1442	2658.8	1449.7
45	1	1441	-4510.0	-779.5
46	1	1441	-5454.1	-2445.5
327	0	1417	-1014.2	-3827.4
701	1	1442	936.3	911.0
707	1	1447	3549.1	-5359.1
708	1	1447	3556.6	-6232.8
709	0	1416	969.2	-1825.5
710	0	1425	1262.2	-2579.4
767	1	1441	-4917.4	-1375.5
788	0	1435	-10443.7	-3277.5
789	1	1446	-7139.1	-3752.1
790	1	1444	-4395.0	215.6
791	1	1445	-3680.2	-4388.5
792	0	1424	234.9	-2127.8
794	1	1452	6723.5	-4662.5
795	1	1443	-1657.8	3097.9
796	1	1444	-4435.0	3276.7
798	1	1448	6439.3	412.0
799	1	1443	202.5	1308.2
907	1	1438	10479.6	812.3
908	1	1438	10756.2	921.3
909	1	1438	10050.6	1031.2
911	1	1438	9864.2	1557.4
912	1	1438	10316.4	1200.6
913	1	1411	637.0	-4534.0
929	1	1411	726.3	-4242.4
947	0	1426	-5488.0	-658.7
948	0	1432	-5858.7	-2004.1
949	0	1429	-8676.6	-119.6
950	0	1431	-9948.4	69.2
951	0	1431	-9901.1	378.2
954	0	1429	-9067.3	-334.0
955	0	1433	-9281.3	-3318.8
956	0	1433	-8674.1	-2290.1
1007	0	1434	-13751.4	-18.3
1008	0	1433	-8970.8	-2002.7
1010	0	1424	-1194.1	-2119.2
1011	0	1435	-11112.2	-2335.6
1012	0	1435	-10803.2	-3739.0
1013	0	1435	-10429.9	-3828.5
1014	0	1417	-1778.2	-1513.2
1015	0	1424	316.9	-2119.3
1016	0	1420	2046.1	1829.4
1017	0	1422	3035.3	-2773.9
1018	0	1423	2484.0	-5183.8
1027	0	1418	-6092.0	-3179.4
1028	0	1427	-7320.6	-2265.1
1029	0	1429	-9615.7	667.3
1030	0	1429	-9184.5	-605.9
1031	0	1434	-14179.6	718.0
1032	0	1432	-4817.8	-2666.7
1033	0	1437	-4055.0	-3448.5
1047	1	1412	-1501.5	-1036.2
1048	1	1448	4619.4	25.6
1049	1	1448	5056.0	220.8
1050	1	1448	6870.6	-662.4
1067	1	1411	-1668.5	-4329.2
1068	1	1411	-838.0	-2037.0
1087	1	1445	-3723.6	-2535.2
1088	1	1445	-2829.8	-2722.8
1089	1	1445	-2884.8	-3430.0
1090	1	1445	-2685.3	-3087.6
1091	1	1445	-3925.5	-2862.1
1092	1	1441	-4301.0	-4062.7
1093	1	1441	-4346.0	-3321.1
1094	1	1441	-4698.1	-3720.6
1095	1	1441	-4987.7	-3833.0
1096	1	1441	-4335.0	-2639.5
1097	1	1445	-3476.6	-4109.1
1098	1	1445	-2949.5	-3893.5
1104	1	1449	-6143.2	-1078.9
1105	1	1449	-6370.1	-1836.5
1106	1	1446	-7693.5	-4879.0
1107	1	1446	-9635.4	-2787.2
1108	1	1441	-5086.2	-1919.4
1109	1	1441	-5466.7	-1636.3
1110	1	1441	-6239.4	-3973.1
1111	1	1441	-6490.6	-3449.1
1112	1	1441	-5065.6	-2367.6
1113	1	1441	-5213.9	-2794.5
1114	1	1441	-5848.0	-3412.4
1115	1	1441	-5799.9	-3899.5
1116	1	1441	-6569.9	-3895.0
1127	0	1430	-11076.0	-1140.0
1128	0	1430	-10349.7	-1538.8
1147	1	1443	-2281.9	2499.6
1148	1	1443	-1422.6	2918.4
1149	1	1443	-1224.1	1736.7
1150	1	1443	-1407.9	1493.1
1151	1	2652	-2251.2	1513.6
1168	1	1444	-3842.7	1738.9
1169	1	1444	-4852.9	3616.6
1171	1	1451	-6206.2	1766.9
1172	1	1451	-6740.0	1636.3
1173	1	1451	-7929.1	1833.3
1174	1	1444	-4915.8	199.3
1175	1	1444	-4052.7	81.6
1176	0	1428	-7652.5	-3030.6
1177	0	1427	-7479.8	-2186.4
1187	1	1444	-5492.4	3622.8
1211	1	1447	3705.1	-6043.5
1212	1	1448	6900.6	-2298.2
1213	1	1452	6426.8	-4305.0
1214	1	1452	5718.8	-4507.3
1215	1	1447	2707.7	-3869.2
1216	1	1447	2195.7	-6438.3
1217	1	1452	7123.0	-4631.6
1218	1	1448	6817.8	-2097.7
1219	1	1448	6481.9	-1571.0
1220	1	1448	5112.0	-353.4
1227	1	1442	515.8	624.0
1228	1	1442	1543.6	70.1
1229	1	1442	981.9	-358.9
1230	1	1442	1531.9	-576.6
1231	1	1442	2416.9	1792.4
1232	1	1448	3493.9	-119.6
1233	1	1448	3827.4	-161.3
1234	1	1448	3362.2	1010.2
1235	1	1440	2231.2	-2222.9
1237	1	1440	2936.6	-2822.7
1238	1	1447	2880.3	-3287.5
1239	1	1411	1702.4	-3151.0
1240	1	1411	1776.6	-2065.1
1241	1	1411	1776.2	-2678.4
1242	1	1442	2130.3	-1190.2
1243	1	1442	2291.3	-1445.0
1244	1	1442	1612.5	-1465.1
1245	1	1442	1930.3	-732.7
1246	1	1450	7856.2	-2215.4
1247	1	1450	7961.8	-2491.8
1248	1	1450	7564.5	-2951.7
1268	1	1411	1575.9	-2463.9
1287	0	1430	-10443.3	-2141.1
1288	0	1430	-10572.0	-1841.1
1289	0	1430	-10740.8	-1973.7
1307	0	1416	921.1	-1421.5
1469	1	1445	-2352.7	-1921.7
1471	1	1440	2286.4	-2564.7
1472	1	1451	-7066.8	731.9
1473	1	1451	-7234.6	874.2
1475	1	1444	-4835.2	863.0
1507	0	1425	-573.5	-4590.5
1508	0	1427	-6513.7	-1142.8
1512	1	1411	1035.1	-2113.3
1513	1	1440	1462.5	-1858.9
1551	0	1422	2249.6	-2389.6
1567	1	1451	-6404.3	-292.6
1588	0	1434	-11874.6	1250.7
1683	0	1435	-10854.8	-4093.4
1685	1	1451	-6886.1	718.4
1687	1	1451	-6996.1	1195.0
1688	1	1451	-6517.5	97.6
1689	1	1451	-6310.1	136.6
1690	1	1451	-7586.2	226.4
1694	1	1451	-8021.8	1105.8
1702	0	1421	1233.1	1214.3
1703	0	1421	908.8	1255.6
1749	0	1423	2562.3	-4797.0
1756	0	1422	2967.5	-3034.4
1763	0	1423	3170.3	-4376.5
1770	0	1422	1853.5	-3723.2
7713	0	1434	-13227.9	229.3
7714	0	1434	-11825.8	99.1
7715	0	1434	-11962.1	-925.4
7716	0	1434	-12720.2	-489.4
7717	0	1434	-13677.7	-256.2
]],
}
local names = {
    enUS = {
        flights = [[
1	Northshire Abbey
2	Stormwind, Elwynn
4	Sentinel Hill, Westfall
5	Lakeshire, Redridge
6	Ironforge, Dun Morogh
7	Menethil Harbor, Wetlands
8	Thelsamar, Loch Modan
9	Booty Bay, Stranglethorn
10	The Sepulcher, Silverpine Forest
11	Undercity, Tirisfal
12	Darkshire, Duskwood
13	Tarren Mill, Hillsbrad
14	Southshore, Hillsbrad
15	Eastern Plaguelands
16	Refuge Pointe, Arathi
17	Hammerfall, Arathi
18	Booty Bay, Stranglethorn
19	Booty Bay, Stranglethorn
20	Grom'gol, Stranglethorn
21	Kargath, Badlands
22	Thunder Bluff, Mulgore
23	Orgrimmar, Durotar
24	Generic, World target for Zeppelin Paths
25	Crossroads, The Barrens
26	Auberdine, Darkshore
27	Rut'theran Village, Teldrassil
28	Astranaar, Ashenvale
29	Sun Rock Retreat, Stonetalon Mountains
30	Freewind Post, Thousand Needles
31	Thalanaar, Feralas
32	Theramore, Dustwallow Marsh
33	Stonetalon Peak, Stonetalon Mountains
34	Transport, Booty Bay - Ratchet
35	Transport, Orgrimmar Zepplins
36	Generic, World target
37	Nijel's Point, Desolace
38	Shadowprey Village, Desolace
39	Gadgetzan, Tanaris
40	Gadgetzan, Tanaris
41	Feathermoon, Feralas
42	Camp Mojache, Feralas
43	Aerie Peak, The Hinterlands
44	Valormok, Azshara
45	Nethergarde Keep, Blasted Lands
46	Southshore Ferry, Hillsbrad
47	Transport, Grom'gol - Orgrimmar
48	Bloodvenom Post, Felwood
49	Moonglade
50	Transport, Menethil Ships
51	Transport, Rut'theran - Auberdine
52	Everlook, Winterspring
53	Everlook, Winterspring
54	Transport, Feathermoon - Feralas
55	Brackenwall Village, Dustwallow Marsh
56	Stonard, Swamp of Sorrows
57	Fishing Village, Teldrassil
58	Zoram'gar Outpost, Ashenvale
61	Splintertree Post, Ashenvale
62	Nighthaven, Moonglade
63	Nighthaven, Moonglade
64	Talrendis Point, Azshara
65	Talonbranch Glade, Felwood
66	Chillwind Camp, Western Plaguelands
67	Light's Hope Chapel, Eastern Plaguelands
68	Light's Hope Chapel, Eastern Plaguelands
69	Moonglade
70	Flame Crest, Burning Steppes
71	Morgan's Vigil, Burning Steppes
72	Cenarion Hold, Silithus
73	Cenarion Hold, Silithus
74	Thorium Point, Searing Gorge
75	Thorium Point, Searing Gorge
76	Revantusk Village, The Hinterlands
77	Camp Taurajo, The Barrens
78	Naxxramas
79	Marshal's Refuge, Un'Goro Crater
80	Ratchet, The Barrens
84	Plaguewood Tower, Eastern Plaguelands
85	Northpass Tower, Eastern Plaguelands
86	Eastwall Tower, Eastern Plaguelands
87	Crown Guard Tower, Eastern Plaguelands
559	Summit of Eternity, Mount Hyjal
3203	Rog'mar, Riverglades
3205	Tidegear Coast, Dun Morogh
3242	Tainted Foothills, Mount Hyjal
3274	Powderfuse Port, Riverglades
3275	Powderfuse Port, Riverglades
3276	Farholde Keep, Riverglades
]],
        towns = [[
1	Anvilmar
2	Brill
3	Darkshire
4	Deathknell
5	Dun Algaz
6	Dun Modr
7	Goldshire
8	Ironforge
9	Kharanos
10	Lakeshire
11	Menethil Harbor
12	Moonbrook
13	Northshire Abbey
14	Raven Hill
15	Sentinel Hill
16	Stormwind
17	The Sepulcher
18	The Undercity
19	Thelsamar
22	Southshore
23	Tarren Mill
24	Refuge Pointe
25	Hammerfall
26	Kargath
27	Angor Fortress
28	Bloodhoof Village
29	Thunder Bluff
30	Camp Narache
31	Razor Hill
32	The Den
33	Orgrimmar
34	Sen'jin Village
35	The Crossroads
36	Aldrassil
37	Dolanaar
38	Darnassus
39	Ratchet
40	Booty Bay
41	Grom'gol Base Camp
42	Astranaar
44	Stonetalon Peak
45	Thalanaar
46	Freewind Post
327	Drywhisker Gorge
701	Sun Rock Retreat
707	Temple of Zin-Malor
708	Hetaera's Clutch
709	Uther's Tomb
710	Scholomance
767	Whitereach Post
788	Stonard
789	Gadgetzan
790	Camp Mojache
791	Theramore Isle
792	Aerie Peak
794	Everlook
795	Shadowprey Village
796	Feathermoon Stronghold
798	Auberdine
799	Nijel's Point
907	Aldrassil
908	Shadowthread Cave
909	Fel Rock
911	Ban'ethil Barrow Den
912	The Cleft
913	Razorwind Canyon
929	Tor'kren Farm
947	Steelgrill's Depot
948	Ironband's Compound
949	Echo Ridge Mine
950	Maclure Vineyards
951	Stonefield Farm
954	Northshire Vineyards
955	Tower of Ilgalar
956	Render's Rock
1007	Spirit Den
1008	Rethban Caverns
1010	Boulderfist Outpost
1011	Grosh'gok Compound
1012	Stagalbog Cave
1013	Temple of Atal'Hakkar
1014	The Tower of Arathor
1015	Wildhammer Keep
1016	Night Web's Hollow
1017	Terrorweb Tunnel
1018	Browman Mill
1027	Uldaman
1028	Dustbelch Grotto
1029	Westbrook Garrison
1030	Jasperlode Mine
1031	Janeiro's Point
1032	Algaz Station
1033	Grim Batol
1047	Venture Co. Mine
1048	Blackwood Den
1049	Wildbend River
1050	Cliffspring Falls
1067	Fray Island
1068	Wailing Caverns
1087	Shady Rest Inn
1088	Darkmist Cavern
1089	North Point Tower
1090	Bluefen
1091	Lost Point
1092	Tidefury Cove
1093	Stonemaul Ruins
1094	Onyxia's Lair
1095	Emberstrife's Den
1096	Bloodfen Burrow
1097	Sentry Point
1098	Swamplight Manor
1104	Marshal's Refuge
1105	Fungal Rock
1106	Wavestrider Beach
1107	Uldum
1108	Darkcloud Pinnacle
1109	Roguefeather Den
1110	Mirage Raceway
1111	The Rustmaul Digsite
1112	Splithoof Hold
1113	The Weathered Nook
1114	Ironstone Camp
1115	Weazel's Crater
1116	Tahonda Ruins
1127	Roland's Doom
1128	Beggar's Haunt
1147	Bolgan's Hole
1148	Maraudon
1149	Ghost Walker Post
1150	Scrabblescrew's Camp
1151	Valley of Bones
1168	Rage Scar Hold
1169	Ruins of Solarsal
1171	Ravaged Twilight Camp
1172	Twilight Post
1173	Twilight Outpost
1174	Woodpaw Hills
1175	Lariss Pavillion
1176	Slither Rock
1177	Flame Crest
1187	Shalzaru's Lair
1211	Scalebeard's Cave
1212	Timbermaw Hold
1213	The Ruins of Kel'Theril
1214	Dun Mandarr
1215	Talrendis Point
1216	Rethress Sanctum
1217	Moon Horror Den
1218	Timbermaw Hold
1219	Irontree Cavern
1220	Bloodvenom Post
1227	Sishir Canyon
1228	Cragpool Lake
1229	Windshear Mine
1230	The Talondeep Path
1231	The Talon Den
1232	The Ruins of Ordil'Aran
1233	Bathran's Haunt
1234	Zoram'gar Outpost
1235	Falfarren River
1237	Xavian
1238	Forest Song
1239	Demon Fall Canyon
1240	Silverwing Outpost
1241	The Dor'Danil Barrow Den
1242	Silverwind Refuge
1243	Greenpaw Village
1244	Bloodtooth Camp
1245	The Talondeep Path
1246	Shrine of Remulos
1247	Nighthaven
1248	Stormrage Barrow Dens
1268	Warsong Labor Camp
1287	Ariden's Camp
1288	Deadwind Ravine
1289	Sleeping Gorge
1307	Chillwind Camp
1469	Camp Taurajo
1471	Splintertree Post
1472	The Swarming Pillar
1473	Bones of Grakkarond
1475	Woodpaw Den
1507	Revantusk Village
1508	Thorium Point
1512	Mor'shan Base Camp
1513	Silverwing Grove
1551	The Weeping Cave
1567	Valor's Rest
1588	Yojamba Isle
1683	Misty Reed Post
1685	Cenarion Hold
1687	Twilight Base Camp
1688	Staghelm Point
1689	Twilight's Run
1690	Ortell's Hideout
1694	Bronzebeard Encampment
1702	Ivar's Patch
1703	Valgan's Field
1749	Eastwall Tower
1756	Plaguewood Tower
1763	Northpass Tower
1770	Crown Guard Tower
7713	Altar of the Blood Loa
7714	Altar of the Blood Loa
7715	Altar of the Blood Loa
7716	Altar of the Blood Loa
7717	Altar of the Blood Loa
]],
    },
    deDE = {
        flights = [[
1	Abtei von Nordhain
2	Stormwind, Elwynn
4	Späherkuppe, Westfall
5	Seenhain, Rotkammgebirge
6	Ironforge, Dun Morogh
7	Hafen von Menethil, Sumpfland
8	Thelsamar, Loch Modan
9	Booty Bay, Schlingendorntal
10	Das Grabmal, Silberwald
11	Undercity, Tirisfal
12	Dunkelhain, Dämmerwald
13	Tarrens Mühle, Hillsbrad
14	Southshore, Hillsbrad
15	Die östlichen Pestländer
16	Die Zuflucht, Arathi
17	Hammerfall, Arathi
18	Booty Bay, Schlingendorntal
19	Booty Bay, Schlingendorntal
20	Grom'gol, Schlingendorntal
21	Kargath, Ödland
22	Thunder Bluff, Mulgore
23	Orgrimmar, Durotar
24	Allgemein, Weltziel für Zeppelinrouten
25	Crossroads, Brachland
26	Auberdine, Dunkelküste
27	Rut'theran, Teldrassil
28	Astranaar, Ashenvale
29	Sonnenfels, Steinkrallengebirge
30	Freiwindposten, Tausend Nadeln
31	Thalanaar, Feralas
32	Theramore, Marschen von Dustwallow
33	Steinkrallengipfel, Steinkrallengebirge
34	Transport, Booty Bay - Ratchet
35	Transport, Zeppeline von Orgrimmar
36	Generic, World target
37	Die Nijelspitze, Desolace
38	Shadowprey, Desolace
39	Gadgetzan, Tanaris
40	Gadgetzan, Tanaris
41	Feathermoon, Feralas
42	Camp Mojache, Feralas
43	Aerie Peak, Hinterland
44	Valormok, Azshara
45	Burg Nethergarde, Verwüstete Lande
46	Fähre von Southshore, Hillsbrad
47	Transport, Grom'gol - Orgrimmar
48	Blutgiftposten, Teufelswald
49	Moonglade
50	Transport, Schiffe von Menethil
51	Transport, Rut'theran - Auberdine
52	Everlook, Winterspring
53	Everlook, Winterspring
54	Transport, Feathermoon - Feralas
55	Brackenwall, Marschen von Dustwallow
56	Stonard, Sümpfe des Elends
57	Fischerdorf, Teldrassil
58	Zoram'gar-Außenposten, Ashenvale
61	Splintertreeposten, Ashenvale
62	Nighthaven, Moonglade
63	Nighthaven, Moonglade
64	Talrendisspitze, Azshara
65	Nachtlaublichtung, Teufelswald
66	Chillwind-Lager, westliche Pestländer
67	Kapelle des hoffnungsvollen Lichts, östliche Pestländer
68	Kapelle des hoffnungsvollen Lichts, östliche Pestländer
69	Moonglade
70	Flammenkamm, brennende Steppe
71	Morgans Wacht, brennende Steppe
72	Burg Cenarius, Silithus
73	Burg Cenarius, Silithus
74	Thoriumspitze, sengende Schlucht
75	Thoriumspitze, sengende Schlucht
76	Revantusk, Hinterland
77	Camp Taurajo, Brachland
78	Naxxramas
79	Marshals Zuflucht, Un'Goro-Krater
80	Ratchet, Brachland
84	Pestwaldturm, östliche Pestländer
85	Nordpassturm, östliche Pestländer
86	Ostwallturm, östliche Pestländer
87	Turm der Kronenwache, östliche Pestländer
559	Gipfel der Ewigkeit, Hyjal
3203	Rog'mar, Flusslande
3205	Gezeitengangküste, Dun Morogh
3242	Besudeltes Vorgebirge, Hyjal
3274	Hafen von Powderfuse, Flusslande
3275	Hafen von Powderfuse, Flusslande
3276	Burg Farholde, Flusslande
]],
        towns = [[
1	Anvilmar
2	Brill
3	Dunkelhain
4	Deathknell
5	Dun Algaz
6	Dun Modr
7	Goldhain
8	Ironforge
9	Kharanos
10	Seenhain
11	Der Hafen von Menethil
12	Moonbrook
13	Abtei von Nordhain
14	Rabenflucht
15	Späherkuppe
16	Stormwind
17	Das Grabmal
18	Undercity
19	Thelsamar
22	Southshore
23	Tarrens Mühle
24	Die Zuflucht
25	Hammerfall
26	Kargath
27	Festung Angor
28	Bloodhoof
29	Thunder Bluff
30	Camp Narache
31	Klingenhügel
32	Der Höhlenbau
33	Orgrimmar
34	Sen'jin
35	Crossroads
36	Aldrassil
37	Dolanaar
38	Darnassus
39	Ratchet
40	Booty Bay
41	Das Basislager von Grom'gol
42	Astranaar
44	Der Steinkrallengipfel
45	Thalanaar
46	Freiwindposten
327	Schlucht der Trockenstoppel
701	Sonnenfels
707	Tempel von Zin-Malor
708	Hetaeras Gelege
709	Uthers Grabmal
710	Scholomance
767	Weißgipfelposten
788	Stonard
789	Gadgetzan
790	Camp Mojache
791	Die Insel Theramore
792	Aerie Peak
794	Everlook
795	Shadowprey
796	Festung Feathermoon
798	Auberdine
799	Die Nijelspitze
907	Aldrassil
908	Schattenweberhöhle
909	Teufelsfels
911	Grabhügel von Ban'ethil
912	Die Kluft
913	Klingenschlucht
929	Tor'krens Hof
947	Steelgrills Depot
948	Ironbands Truppenlager
949	Echokammmine
950	Weinberge der Maclures
951	Hof der Stonefields
954	Weinberge von Nordhain
955	Der Turm von Ilgalar
956	Renders Fels
1007	Geisterhöhlenbau
1008	Rethbanhöhlen
1010	Außenposten der Felsfäuste
1011	Das Grosh'gok Lager
1012	Stagalboghöhle
1013	Der Tempel von Atal'Hakkar
1014	Der Turm von Arathor
1015	Burg Wildhammer
1016	Nachtwebergrund
1017	Terrorweb-Tunnel
1018	Braumanns Mühle
1027	Uldaman
1028	Die Staubspeiergrotte
1029	Weststromgarnison
1030	Jaspismine
1031	Janeirospitze
1032	Station Algaz
1033	Grim Batol
1047	Mine der Venture Co.
1048	Bau der Schwarzfelle
1049	Der Wildbend
1050	Cliffspring Falls
1067	Prügel-Eiland
1068	Die Höhlen des Wehklagens
1087	Gasthaus Zur süßen Ruh
1088	Graunebelhöhlen
1089	Nordwacht
1090	Blaumoor
1091	Die verlassene Wacht
1092	Tidefury-Bucht
1093	Die Stonemaul Ruinen
1094	Onyxias Hort
1095	Aschenschwingens Bau
1096	Blutsumpfbau
1097	Späherwacht
1098	Swamplight-Anwesen
1104	Marshals Zuflucht
1105	Fungal Rock
1106	Wellenschreiterstrand
1107	Uldum
1108	Düsterwolkengipfel
1109	Bau der Wildfedern
1110	Illusionenrennbahn
1111	Die Rustmaul-Grabungsstätte
1112	Spalthufhöhle
1113	Der Wetterwinkel
1114	Eisensteinlager
1115	Weazels Krater
1116	Ruinen von Tahonda
1127	Rolands Verdammnis
1128	Bettlerschlupfwinkel
1147	Bolgans Loch
1148	Maraudon
1149	Geistwandlerposten
1150	Scrabblescrews Lager
1151	Tal der Knochen
1168	Wutschrammfeste
1169	Ruinen von Solarsal
1171	Verwüsteter Twilight-Stützpunkt
1172	Twilight-Posten
1173	Twilight-Außenposten
1174	Waldpfotenhügel
1175	Lariss' Pavillon
1176	Schlitterfels
1177	Flammenkamm
1187	Shalzarus Unterschlupf
1211	Schuppenbarts Höhle
1212	Holzschlundfeste
1213	Die Ruinen von Kel'Theril
1214	Dun Mandarr
1215	Talrendisspitze
1216	Rethress Sanktum
1217	Mondschreckensbau
1218	Holzschlundfeste
1219	Eisenstammhöhle
1220	Blutgiftposten
1227	Sishircanyon
1228	Felskesselsee
1229	Scherwindmine
1230	Der Steinkrallenpfad
1231	Der Krallenbau
1232	Die Ruinen von Ordil'Aran
1233	Bathrans Schlupfwinkel
1234	Zoram'gar-Außenposten
1235	Der Falfarren
1237	Xavian
1238	Forest Song
1239	Demonfall-Canyon
1240	Außenposten der Silverwing
1241	Der Dor'danil-Grabhügel
1242	Silberwindzuflucht
1243	Laubtatzenlichtung
1244	Blutreißers Lager
1245	Der Steinkrallenpfad
1246	Schrein von Remulos
1247	Nighthaven
1248	Die Stormrage Grabhügel
1268	Lager der Warsongarbeiter
1287	Aridens Lager
1288	Schlucht der Totenwinde
1289	Die schlummernde Schlucht
1307	Chillwind-Lager
1469	Camp Taurajo
1471	Splintertreeposten
1472	Die Schwarmsäule
1473	Knochen von Grakkarond
1475	Waldpfotenbau
1507	Revantusk
1508	Thoriumspitze
1512	Mor'shan-Stützpunkt
1513	Hain der Silverwing
1551	Die weinende Höhle
1567	Heldenwacht
1588	Die Insel Yojamba
1683	Nebelschilfposten
1685	Burg Cenarius
1687	Basislager der Twilight
1688	Staghelms Stätte
1689	Kavernen der Twilight
1690	Ortells Unterschlupf
1694	Bronzebeards Lager
1702	Invar-Feld
1703	Valgans Feld
1749	Ostwallturm
1756	Pestwaldturm
1763	Nordpassturm
1770	Turm der Kronenwache
7713	Altar des Blutloas
7714	Altar des Blutloas
7715	Altar des Blutloas
7716	Altar des Blutloas
7717	Altar des Blutloas
]],
    },
    frFR = {
        flights = [[
1	Abbaye de Comté-du-Nord
2	Stormwind, Elwynn
4	Colline des sentinelles, marche de l'Ouest
5	Comté-du-Lac, les Carmines
6	Forgefer, Dun Morogh
7	Port de Menethil, les Paluns
8	Thelsamar, Loch Modan
9	Baie-du-Butin, Strangleronce
10	Le Sépulcre, forêt des Pins argentés
11	Fossoyeuse, Tirisfal
12	Darkshire, bois de la Pénombre
13	Moulin-de-Tarren, Hillsbrad
14	Austrivage, Hillsbrad
15	Maleterres de l'est
16	Refuge de l'Ornière, Arathi
17	Trépas-d'Orgrim, Arathi
18	Baie-du-Butin, Strangleronce
19	Baie-du-Butin, Strangleronce
20	Grom'gol, Strangleronce
21	Kargath, Terres ingrates
22	Thunder Bluff, Mulgore
23	Orgrimmar, Durotar
24	Générique, Cible monde pour les voies des zeppelins
25	La Croisée, Tarides
26	Auberdine, Sombrivage
27	Rut'theran, Teldrassil
28	Astranaar, Ashenvale
29	Retraite de Roche-Soleil, Serres-Rocheuses
30	Poste de Librevent, Mille Pointes
31	Thalanaar, Feralas
32	Theramore, marécage d'Âprefange
33	Pic des Serres-Rocheuses, Serres-Rocheuses
34	Transport, Ratchet - Baie-du-Butin
35	Transport, zeppelins d'Orgrimmar
36	Générique, cible monde
37	Combe de Nijel, Désolace
38	Proie-de-l'Ombre, Désolace
39	Gadgetzan, Tanaris
40	Gadgetzan, Tanaris
41	Feathermoon, Feralas
42	Camp Mojache, Feralas
43	Nid-de-l'Aigle, Les Hinterlands
44	Valormok, Azshara
45	Rempart-du-Néant, Terres foudroyées
46	Bac d’Austrivage, Hillsbrad
47	Transport, Grom'gol - Orgrimmar
48	Poste de la Vénéneuse, Gangrebois
49	Reflet-de-Lune
50	Transport, vaisseaux de Menethil
51	Transport, Rut'theran - Auberdine
52	Long-guet, Berceau-de-l'Hiver
53	Long-guet, Berceau-de-l'Hiver
54	Transport, Feathermoon - Feralas
55	Mur-de-Fougères, marécage d'Âprefange
56	Pierrêche, marais des Chagrins
57	Village de pêcheurs, Teldrassil
58	Avant-poste de Zoram'gar, Ashenvale
61	Poste de Bois-brisé, Ashenvale
62	Havrenuit, Reflet-de-Lune
63	Havrenuit, Reflet-de-Lune
64	Halte de Talrendis, Azshara
65	Clairière de Griffebranche, Gangrebois
66	Camp du Noroît, Maleterres de l'ouest
67	Chapelle de l'Espoir de Lumière, Maleterres de l'est
68	Chapelle de l'Espoir de Lumière, Maleterres de l'est
69	Reflet-de-Lune
70	Corniches des flammes, Steppes ardentes
71	Veille de Morgan, Steppes ardentes
72	Fort cénarien, Silithus
73	Fort cénarien, Silithus
74	Halte du Thorium, Gorge des Vents brûlants
75	Halte du Thorium, Gorge des Vents brûlants
76	Village des Revantusk, les Hinterlands
77	Camp Taurajo, les Tarides
78	Naxxramas
79	Refuge des Marshal, cratère d'Un'Goro
80	Ratchet, les Tarides
84	Tour de Pestebois, Maleterres de l'est
85	Tour du Col du nord, Maleterres de l'est
86	Tour du Mur d'est, Maleterres de l'est
87	Tour de garde de la couronne, Maleterres de l'est
559	Sommet d’Éternité, mont Hyjal
3203	Rog’mar, rives Claires
3205	Côte de Vaguerouage, Dun Morogh
3242	Contreforts Souillés, mont Hyjal
3274	Port de Poudremèche, rives Claires
3275	Port de Poudremèche, rives Claires
3276	Donjon de Fort-Lointain, rives Claires
]],
        towns = [[
1	Courbenclume
2	Brill
3	Darkshire
4	Le Glas
5	Dun Algaz
6	Dun Modr
7	Comté-de-l’Or
8	Forgefer
9	Kharanos
10	Comté-du-Lac
11	Port de Menethil
12	Ruisselune
13	Abbaye de Comté-du-Nord
14	Colline-aux-Corbeaux
15	Colline des sentinelles
16	Stormwind
17	Le Sépulcre
18	Fossoyeuse
19	Thelsamar
22	Austrivage
23	Moulin-de-Tarren
24	Refuge de l'Ornière
25	Trépas-d'Orgrim
26	Kargath
27	Forteresse d'Angor
28	Sabot-de-Sang
29	Thunder Bluff
30	Camp Narache
31	Tranchecolline
32	L'Antre
33	Orgrimmar
34	Village de Sen'jin
35	La Croisée
36	Aldrassil
37	Dolanaar
38	Darnassus
39	Ratchet
40	Baie-du-Butin
41	Campement Grom'gol
42	Astranaar
44	Pic des Serres-Rocheuses
45	Thalanaar
46	Poste de Librevent
327	Gorge des Sèches-moustaches
701	Retraite de Roche-Soleil
707	Temple de Zin-Malor
708	Frai d'Hetaera
709	Tombeau d'Uther
710	Scholomance
767	Poste de Blanc-relais
788	Pierrêche
789	Gadgetzan
790	Camp Mojache
791	Ile de Theramore
792	Nid-de-l'Aigle
794	Long-guet
795	Proie-de-l'Ombre
796	Bastion de Feathermoon
798	Auberdine
799	Combe de Nijel
907	Aldrassil
908	Grotte de Sombrefil
909	Gangreroche
911	Refuge des saisons de Ban'ethil
912	La Faille
913	Canyon de Tranchevent
929	Ferme de Tor'kren
947	Dépôt de Steelgrill
948	Base d'Ironband
949	Mine de la crête aux échos
950	Vignes des Maclure
951	Ferme des Stonefield
954	Vignoble de Comté-du-Nord
955	Tour d'Ilgalar
956	Rocher des Etripeurs
1007	Antre des esprits
1008	Cavernes de Rethban
1010	Avant-poste Rochepoing
1011	Base des Grosh'gok
1012	Caverne de Stagalbog
1013	Temple d'Atal'Hakkar
1014	La tour d'Arathor
1015	Donjon des Wildhammer
1016	Grottes des Tisse-nuit
1017	Tunnel de Tisse-terreur
1018	Scierie de Browman
1027	Uldaman
1028	Grotte de Crache-poussière
1029	Garnison du ruisseau de l'ouest
1030	Mine Veine-de-jaspe
1031	Cap Janeiro
1032	Poste d'Algaz
1033	Grim Batol
1047	Mine de la KapitalRisk
1048	Tanière des Noirbois
1049	La Sinueuse
1050	Chutes de la Bondissante
1067	Ile de la Dispute
1068	Cavernes des lamentations
1087	Auberge du Repos ombragé
1088	Caverne de Sombrebrume
1089	Tour de la halte nord
1090	Marais bleu
1091	Halte perdue
1092	Crique du Mascaret
1093	Ruines Cognepierres
1094	Le repaire d'Onyxia
1095	Tanière de Brandeguerre
1096	Terrier des Rougefanges
1097	Halte de la Vigie
1098	Manoir des Flammeroles
1104	Refuge des Marshal
1105	Rocher fongique
1106	Plage des Déferlantes
1107	Uldum
1108	Cime de Noir-nuage
1109	Tanière des Volplumes
1110	Piste des mirages
1111	Site de fouilles de Rustmaul
1112	Bastion du Sabot fendu
1113	La niche érodée
1114	Camp Rochefer
1115	Cratère de Weazel
1116	Ruines de Tahonda
1127	Destin de Roland
1128	Repaire des mendiants
1147	Trou de Bolgan
1148	Maraudon
1149	Poste de Rôdeur-fantôme
1150	Camp de Scrabblescrew
1151	Vallée des Ossements
1168	Repaire des Griffes féroces
1169	Ruines de Solarsal
1171	Camp du Crépuscule ravagé
1172	Poste du Crépuscule
1173	Avant-poste du Crépuscule
1174	Collines des Griffebois
1175	Pavillon de Lariss
1176	Roc sinueux
1177	Corniche des flammes
1187	Antre de Shalzaru
1211	Caverne de Barbe-d'écailles
1212	Repaire des Grumegueules
1213	Les ruines de Kel'Theril
1214	Dun Mandarr
1215	Halte de Talrendis
1216	Sanctuaire de Rethress
1217	Antre de l'Horreur lunaire
1218	Repaire des Grumegueules
1219	Caverne d'Arbrefer
1220	Poste de la Vénéneuse
1227	Canyon de Sishir
1228	Lac de la Combe
1229	Mine des Cisailles
1230	La Perce des Serres
1231	L'antre des Serres
1232	Les ruines d'Ordil'Aran
1233	Repaire de Bathran
1234	Avant-poste de Zoram'gar
1235	Fleuve Falfarren
1237	Xavian
1238	Chant des forêts
1239	Canyon de la Malechute
1240	Avant-poste d'Aile-argent
1241	Le Refuge des saisons de Dor'danil
1242	Refuge de Vent-argent
1243	Village des Pattes-vertes
1244	Camp de Dent-rouge
1245	La Perce des Serres
1246	Sanctuaire de Remulos
1247	Havrenuit
1248	Refuge des saisons de Malfurion
1268	Camp de travail chanteguerre
1287	Camp d'Ariden
1288	Ravin de Deuillevent
1289	Gorge endormie
1307	Camp du Noroît
1469	Camp Taurajo
1471	Poste de Bois-brisé
1472	Le pilier grouillant
1473	Restes de Grakkarond
1475	Tanière des Griffebois
1507	Village des Revantusk
1508	Halte du Thorium
1512	Campement de Mor'shan
1513	Bosquet d'Aile-argent
1551	La grotte des Pleurs
1567	Le Repos des Vaillants
1588	Ile de Yojamba
1683	Poste de Brumejonc
1685	Fort cénarien
1687	Campement du crépuscule
1688	Halte de Staghelm
1689	Défilé du crépuscule
1690	La planque d'Ortell
1694	Campement de Bronzebeard
1702	Lopin d'Ivar
1703	Champ de Valgan
1749	Tour du Mur d'est
1756	Tour de Pestebois
1763	Tour du Col du nord
1770	Tour de garde de la couronne
7713	Autel du Loa du sang
7714	Autel du Loa du sang
7715	Autel du Loa du sang
7716	Autel du Loa du sang
7717	Autel du Loa du sang
]],
    },
    esES = {
        flights = [[
1	Abadía de Villanorte
2	Ventormenta, Elwynn
4	Colina del Centinela, Páramos de Poniente
5	Villa del Lago, Crestagrana
6	Forjaz, Dun Morogh
7	Puerto de Menethil, Los Humedales
8	Thelsamar, Loch Modan
9	Bahía del Botín, Tuercespina
10	El Sepulcro, Bosque de Argénteos
11	Entrañas, Tirisfal
12	Villa Oscura, Bosque del Ocaso
13	Molino Tarren, Trabalomas
14	Costasur, Trabalomas
15	Tierras de la Peste del Este
16	Refugio de la Zaga, Arathi
17	Sentencia, Arathi
18	Bahía del Botín, Tuercespina
19	Bahía del Botín, Tuercespina
20	Grom'gol, Tuercespina
21	Kargath, Tierras Inhóspitas
22	Cima del Trueno, Mulgore
23	Orgrimmar, Durotar
24	Genérico, Objetivo mundial para rutas de zeppelines
25	El Cruce, Los Baldíos
26	Auberdine, Costa Oscura
27	Aldea Rut'theran, Teldrassil
28	Astranaar, Vallefresno
29	Refugio Roca del sol, Sierra Espolón
30	Poblado Viento Libre, Las Mil Agujas
31	Thalanaar, Feralas
32	Theramore, Marjal Revolcafango
33	Cima del Espolón, Sierra Espolón
34	Transporte, Bahía del Botín - Trinquete
35	Transporte, Zeppelines de Orgrimmar
36	Genérico, Objetivo mundial
37	Punta de Nijel, Desolace
38	Aldea Cazasombras, Desolace
39	Gadgetzan, Tanaris
40	Gadgetzan, Tanaris
41	Plumaluna, Feralas
42	Campamento Mojache, Feralas
43	Pico Nidal, Tierras del Interior
44	Valormok, Azshara
45	Castillo de Nethergarde, Las Tierras Devastadas
46	Embarcadero de Costasur, Trabalomas
47	Transporte, Grom'gol - Orgrimmar
48	Puesto del Veneno
49	Claro de la Luna
50	Transporte, Barcos de Menethil
51	Transporte, Rut'theran - Auberdine
52	Vista Eterna, Cuna del Invierno
53	Vista Eterna, Cuna del Invierno
54	Transporte, Plumaluna - Feralas
55	Poblado Murohelecho, Marjal Revolcafango
56	Rocal, Pantano de las Penas
57	Aldea Pesquera, Teldrassil
58	Avanzada de Zoram'gar, Vallefresno
61	Puesto del Hachazo, Vallefresno
62	Amparo de la Noche, Claro de la Luna
63	Amparo de la Noche, Claro de la Luna
64	Punta Talrendis, Azshara
65	Claro Ramaespolón, Frondavil
66	Campamento del Orvallo, Tierras de la Peste del Oeste
67	Capilla de la Esperanza de la Luz, Tierras de la Peste del Este
68	Capilla de la Esperanza de la Luz, Tierras de la Peste del Este
69	Claro de la Luna
70	Peñasco Llamarada, Las Estepas Ardientes
71	Vigilia de Morgan, Las Estepas Ardientes
72	Fuerte Cenarion, Silithus
73	Fuerte Cenarion, Silithus
74	Puesto del Thorium, La Garganta de Fuego
75	Puesto del Thorium, La Garganta de Fuego
76	Poblado Sañadiente, Tierras del Interior
77	Campamento Taurajo, Los Baldíos
78	Naxxramas
79	Refugio de Marshal, Cráter de Un'Goro
80	Trinquete, Los Baldíos
84	Torre del Bosque de la Peste, Tierras de la Peste de Este
85	Torre del Paso Norte, Tierras de la Peste del Este
86	Torre de la Muralla del Este, Tierras de la Peste del Este
87	Torre de la Corona, Tierras de la Peste del Este
559	Cima de la Eternidad, Monte Hyjal
3203	Rog'mar, Clarofluvial
3205	Costa Mareanaje, Dun Morogh
3242	Laderas Máculas, Monte Hyjal
3274	Puerto Polvofusil, Clarofluvial
3275	Puerto Polvofusil, Clarofluvial
3276	Castillo de Farholde, Clarofluvial
]],
        towns = [[
1	Yunquemar
2	Rémol
3	Villa Oscura
4	Camposanto
5	Dun Algaz
6	Dun Modr
7	Villadorada
8	Forjaz
9	Kharanos
10	Villa del Lago
11	Puerto de Menethil
12	Arroyo de la Luna
13	Abadía de Villanorte
14	Cerro del Cuervo
15	Colina del Centinela
16	Ventormenta
17	El Sepulcro
18	Entrañas
19	Thelsamar
22	Costasur
23	Molino Tarren
24	Refugio de la Zaga
25	Sentencia
26	Kargath
27	Fortaleza de Angor
28	Poblado Pezuña de Sangre
29	Cima del Trueno
30	Campamento Narache
31	Cerrotajo
32	El Cubil
33	Orgrimmar
34	Poblado Sen'jin
35	El Cruce
36	Aldrassil
37	Dolanaar
38	Darnassus
39	Trinquete
40	Bahía del Botín
41	Campamento Grom'Gol
42	Astranaar
44	Cima del Espolón
45	Thalanaar
46	Poblado Viento Libre
327	Cañón Mostacho Seco
701	Refugio Roca del Sol
707	Templo de Zin-Malor
708	Guarida de Hetaera
709	Tumba de Uther
710	Scholomance
767	Campamento del Tramo Blanco
788	Rocal
789	Gadgetzan
790	Campamento Mojache
791	Isla Theramore
792	Pico Nidal
794	Vista Eterna
795	Aldea Cazasombras
796	Bastión Plumaluna
798	Auberdine
799	Punta de Nijel
907	Aldrassil
908	Gruta Narácnida
909	Roca Mácula
911	Túmulo de Ban'ethil
912	La Grieta
913	Cañón del Ventajo
929	Granja Tor'kren
947	Almacén de Brasacerada
948	Complejo Vetaferro
949	Mina del Eco
950	Los Viñedos de Maclure
951	La Granja Pedregosa
954	Viñedos de Villanorte
955	Torre de Ilgalar
956	Roca de Render
1007	Cubil del Espíritu
1008	Cavernas de Rethban
1010	Avanzada Puño de Roca
1011	Dominios Grosh'gok
1012	Cueva Stagalbog
1013	Templo de Atal'Hakkar
1014	La Torre de Arathor
1015	Fortaleza de los Martillo Salvaje
1016	Hoya Nocturácnidas
1017	Túnel Terroarácnido
1018	Molino Cejifrente
1027	Uldaman
1028	Gruta Rotapolvo
1029	Cuartel Arroyoeste
1030	Cantera de Jaspe
1031	Cayo de Janeiro
1032	Estación de Algaz
1033	Grim Batol
1047	Mina Riesgo y Cía
1048	Cubil del Bosque Negro
1049	Río Culebra
1050	Salto de Fonroca
1067	Isla de Batalla
1068	Cuevas de los Lamentos
1087	Posada Reposo Umbrío
1088	Cueva de la Niebla Negra
1089	Torre de la Punta Norte
1090	Ciénaga Azul
1091	Punta Perdida
1092	Cala Furiamarea
1093	Ruinas Quebrantarrocas
1094	Guarida de Onyxia
1095	Cubil de Brasaliza
1096	Madriguera de los Cienorrojo
1097	Alto del Centinela
1098	Mansión Cienaluz
1104	Refugio de Marshal
1105	Roca Fungal
1106	Playa Baile de las Olas
1107	Uldum
1108	Cumbre de la Nube Negra
1109	Guarida Malapluma
1110	Circuito del Espejismo
1111	Excavación Oximelena
1112	Campamento Pezuña Quebrada
1113	El Hueco Perdido
1114	Campamento Roca de Hierro
1115	Cráter de la Comadreja
1116	Ruinas de Tahonda
1127	Condena de Roland
1128	Refugio de los Mendigos
1147	Cuenca de Bolgan
1148	Maraudon
1149	Campamento del Espíritu Errante
1150	Campamento de los Mezclatornillos
1151	Valle de los Huesos
1168	Dominios de los Cicatriz de Rabia
1169	Ruinas de Solarsal
1171	Campamento Crepúsculo devastado
1172	Puesto Crepúsculo
1173	Avanzada Crepúsculo
1174	Colinas Zarpaleña
1175	Pabellón de Lariss
1176	Roca Desliz
1177	Peñasco Llamarada
1187	Guarida de Shalzaru
1211	Cueva Barbaescamas
1212	Bastión de los Fauces de Madera
1213	Las Ruinas de Kel'Theril
1214	Dun Mandarr
1215	Punta Talrendis
1216	Sagrario de Rethress
1217	Cubil Pavor Lunar
1218	Bastión de los Fauces de Madera
1219	Caverna de Troncoferro
1220	Puesto del Veneno
1227	Cañón Sishir
1228	Lago del Peñasco
1229	Mina Cortaviento
1230	El Paso del Espolón
1231	El Cubil del Espolón
1232	Las Ruinas de Ordil'Aran
1233	Ruinas de Bathran
1234	Avanzada de Zoram'gar
1235	Río Falfarren
1237	Xavian
1238	Canción del Bosque
1239	Barranco del Demonio
1240	Avanzada Ala de Plata
1241	El Túmulo de Dor'danil
1242	Refugio Brisa de Plata
1243	Poblado Zarpaverde
1244	Asentamiento Sangradientes
1245	El Paso del Espolón
1246	Santuario de Remulos
1247	Amparo de la Noche
1248	Túmulos de Tempestira
1268	Campo de trabajos forzados Grito de Guerra
1287	Campamento de Ariden
1288	Barranco de la Muerte
1289	Desfiladero del Letargo
1307	Campamento del Orvallo
1469	Campamento Taurajo
1471	Puesto del Hachazo
1472	El Pilar de la Ascensión
1473	Huesos de Grakkarond
1475	Guarida de los Zarpaleña
1507	Poblado Sañadiente
1508	Puesto del Torio
1512	Campamento de Mor'shan
1513	Claro Ala de Plata
1551	La Cueva del Llanto
1567	Sosiego del Valor
1588	Isla Yojamba
1683	Puesto Juncobruma
1685	Fuerte Cenarion
1687	Campamento Crepúsculo
1688	Punta de Corzocelada
1689	Paseo Crepúsculo
1690	Guarida de Ortell
1694	Campamento Barbabronce
1702	Los Dominios de Ivar
1703	Campo de Valgan
1749	Torre de la Muralla del Este
1756	Torre del Bosque de la Peste
1763	Torre del Paso Norte
1770	Torre de la Corona
7713	Altar del loa de la sangre
7714	Altar del loa de la sangre
7715	Altar del loa de la sangre
7716	Altar del loa de la sangre
7717	Altar del loa de la sangre
]],
    },
    esMX = {
        flights = [[
1	Abadía de Villanorte
2	Ventormenta, Elwynn
4	Colina del Centinela, Páramos de Poniente
5	Villa del Lago, Crestagrana
6	Forjaz, Dun Morogh
7	Puerto de Menethil, Los Humedales
8	Thelsamar, Loch Modan
9	Bahía del Botín, Tuercespina
10	El Sepulcro, Bosque de Argénteos
11	Entrañas, Tirisfal
12	Villa Oscura, Bosque del Ocaso
13	Molino Tarren, Trabalomas
14	Costasur, Trabalomas
15	Tierras de la Peste del Este
16	Refugio de la Zaga, Arathi
17	Sentencia, Arathi
18	Bahía del Botín, Tuercespina
19	Bahía del Botín, Tuercespina
20	Grom'gol, Tuercespina
21	Kargath, Tierras Inhóspitas
22	Cima del Trueno, Mulgore
23	Orgrimmar, Durotar
24	Genérico, Objetivo mundial de rutas de zepelines
25	El Cruce, Los Baldíos
26	Auberdine, Costa Oscura
27	Aldea Rut'theran, Teldrassil
28	Astranaar, Vallefresno
29	Refugio Roca del Sol, Sierra Espolón
30	Poblado Viento Libre, Las Mil Agujas
31	Thalanaar, Feralas
32	Theramore, Marjal Revolcafango
33	Cima del Espolón, Sierra Espolón
34	Transporte: Bahía del Botín a Trinquete
35	Transporte, Zepelines de Orgrimmar
36	Genérico, Objetivo mundial
37	Punta de Nijel, Desolace
38	Aldea Cazasombras, Desolace
39	Gadgetzan, Tanaris
40	Gadgetzan, Tanaris
41	Plumaluna, Feralas
42	Campamento Mojache, Feralas
43	Pico Nidal, Tierras del Interior
44	Valormok, Azshara
45	Castillo de Nethergarde, Las Tierras Devastadas
46	Transbordador de Costasur, Trabalomas
47	Transporte: Grom'gol a Orgrimmar
48	Puesto del Veneno, Frondavil
49	Claro de la Luna
50	Transporte, Naves de Menethil
51	Transporte: Rut'theran a Auberdine
52	Vista Eterna, Cuna del Invierno
53	Vista Eterna, Cuna del Invierno
54	Transporte: Plumaluna a Feralas
55	Poblado Murohelecho, Marjal Revolcafango
56	Rocal, Pantano de las Penas
57	Aldea Pesquera, Teldrassil
58	Avanzada de Zoram'gar, Vallefresno
61	Puesto del Hachazo, Vallefresno
62	Amparo de la Noche, Claro de la Luna
63	Amparo de la Noche, Claro de la Luna
64	Punta Talrendis, Azshara
65	Claro Ramaespolón, Frondavil
66	Campamento del Orvallo, Tierras de la Peste del Oeste
67	Capilla de la Esperanza de la Luz, Tierras de la Peste del Este
68	Capilla de la Esperanza de la Luz, Tierras de la Peste del Este
69	Claro de la Luna
70	Peñasco Llamarada, Las Estepas Ardientes
71	Vigilia de Morgan, Las Estepas Ardientes
72	Fuerte Cenarion, Silithus
73	Fuerte Cenarion, Silithus
74	Puesto del Torio, La Garganta de Fuego
75	Puesto del Torio, La Garganta de Fuego
76	Poblado Sañadiente, Tierras del Interior
77	Campamento Taurajo, Los Baldíos
78	Naxxramas
79	Refugio de Marshal, Cráter de Un'Goro
80	Trinquete, Los Baldíos
84	Torre del Bosque de la Peste, Tierras de la Peste de Este
85	Torre del Paso Norte, Tierras de la Peste del Este
86	Torre de la Muralla del Este, Tierras de la Peste del Este
87	Torre de la Corona, Tierras de la Peste del Este
559	Cima de la Eternidad, Monte Hyjal
3203	Rog'mar, Claros del Río
3205	Costa Acoplamarea, Dun Morogh
3242	Laderas Maculadas, Monte Hyjal
3274	Puerto Polvomecha, Claros del Río
3275	Puerto Polvomecha, Claros del Río
3276	Fortaleza de Farholde, Claros del Río
]],
        towns = [[
1	Yunquemar
2	Rémol
3	Villa Oscura
4	Camposanto
5	Dun Algaz
6	Dun Modr
7	Villadorada
8	Forjaz
9	Kharanos
10	Villa del Lago
11	Puerto de Menethil
12	Arroyo de la Luna
13	Abadía de Villanorte
14	Cerro del Cuervo
15	Colina del Centinela
16	Ventormenta
17	El Sepulcro
18	Entrañas
19	Thelsamar
22	Costasur
23	Molino Tarren
24	Refugio de la Zaga
25	Sentencia
26	Kargath
27	Fortaleza de Angor
28	Poblado Pezuña de Sangre
29	Cima del Trueno
30	Campamento Narache
31	Cerrotajo
32	El Cubil
33	Orgrimmar
34	Poblado Sen'jin
35	El Cruce
36	Aldrassil
37	Dolanaar
38	Darnassus
39	Trinquete
40	Bahía del Botín
41	Campamento Grom'Gol
42	Astranaar
44	Cima del Espolón
45	Thalanaar
46	Poblado Viento Libre
327	Cañón Mostacho Seco
701	Refugio Roca del Sol
707	Templo de Zin-Malor
708	Guarida de Hetaera
709	Tumba de Uther
710	Scholomance
767	Campamento del Tramo Blanco
788	Rocal
789	Gadgetzan
790	Campamento Mojache
791	Isla Theramore
792	Pico Nidal
794	Vista Eterna
795	Aldea Cazasombras
796	Bastión Plumaluna
798	Auberdine
799	Punta de Nijel
907	Aldrassil
908	Gruta Narácnida
909	Roca Mácula
911	Túmulo de Ban'ethil
912	La Grieta
913	Cañón del Ventajo
929	Granja Tor'kren
947	Almacén de Brasacerada
948	Complejo Vetaferro
949	Mina del Eco
950	Los Viñedos de Maclure
951	La Granja Pedregosa
954	Viñedos de Villanorte
955	Torre de Ilgalar
956	Roca de Render
1007	Cubil del Espíritu
1008	Cavernas de Rethban
1010	Avanzada Puño de Roca
1011	Dominios Grosh'gok
1012	Cueva Stagalbog
1013	Templo de Atal'Hakkar
1014	Torre de Arathor
1015	Fortaleza de los Martillo Salvaje
1016	Hoya Nocturácnidas
1017	Túnel Terroarácnido
1018	Molino Cejifrente
1027	Uldaman
1028	Gruta Rotapolvo
1029	Cuartel de Arroyoeste
1030	Cantera de Jaspe
1031	Cayo de Janeiro
1032	Estación de Algaz
1033	Grim Batol
1047	Mina Ventura y Cía.
1048	Cubil del Bosque Negro
1049	Río Culebra
1050	Salto de Fonroca
1067	Isla de Batalla
1068	Cuevas de los Lamentos
1087	Posada Reposo Umbrío
1088	Cueva Niebla Negra
1089	Torre de la Punta Norte
1090	Ciénaga Azul
1091	Punta Perdida
1092	Cala Furiamarea
1093	Ruinas Quebrantarrocas
1094	Guarida de Onyxia
1095	Cubil de Brasaliza
1096	Madriguera de los Cienorrojo
1097	Alto del Centinela
1098	Mansión Cienaluz
1104	Refugio de Marshal
1105	Roca Fungal
1106	Playa Baile de las Olas
1107	Uldum
1108	Cumbre de la Nube Negra
1109	Guarida Malapluma
1110	Circuito del Espejismo
1111	Excavación Oximelena
1112	Campamento Pezuña Quebrada
1113	El Hueco Perdido
1114	Campamento Roca de Hierro
1115	Cráter de la Comadreja
1116	Ruinas de Tahonda
1127	Condena de Roland
1128	Refugio de los Mendigos
1147	Cuenca de Bolgan
1148	Maraudon
1149	Campamento del Espíritu Errante
1150	Campamento de los Mezclatornillos
1151	Valle de los Huesos
1168	Dominios de los Cicatriz de Rabia
1169	Ruinas de Solarsal
1171	Campamento Crepúsculo Devastado
1172	Puesto Crepúsculo
1173	Avanzada Crepúsculo
1174	Colinas Zarpaleña
1175	Pabellón de Lariss
1176	Roca Desliz
1177	Peñasco Llamarada
1187	Guarida de Shalzaru
1211	Cueva de Barbaescamas
1212	Bastión Fauces de Madera
1213	Las Ruinas de Kel'Theril
1214	Dun Mandarr
1215	Punta Talrendis
1216	Sagrario de Rethress
1217	Cubil del Horror de la Luna
1218	Bastión Fauces de Madera
1219	Caverna de Troncoferro
1220	Puesto del Veneno
1227	Cañón Sishir
1228	Lago del Peñasco
1229	Mina Cortaviento
1230	El Paso del Espolón
1231	El Cubil del Espolón
1232	Las Ruinas de Ordil'Aran
1233	Ruinas de Bathran
1234	Avanzada de Zoram'gar
1235	Río Falfarren
1237	Xavian
1238	Canción del Bosque
1239	Barranco del Demonio
1240	Avanzada Ala de Plata
1241	El Túmulo de Dor'danil
1242	Refugio Brisa de Plata
1243	Poblado Zarpaverde
1244	Asentamiento Sangradientes
1245	El Paso del Espolón
1246	Santuario de Remulos
1247	Amparo de la Noche
1248	Túmulo de Tempestira
1268	Campo de trabajos forzados Grito de Guerra
1287	Campamento de Ariden
1288	Barranco de la Muerte
1289	Desfiladero del Letargo
1307	Campamento del Orvallo
1469	Campamento Taurajo
1471	Puesto del Hachazo
1472	El Pilar de la Ascensión
1473	Huesos de Grakkarond
1475	Guarida de los Zarpaleña
1507	Poblado Sañadiente
1508	Puesto del Torio
1512	Campamento de Mor'shan
1513	Claro Ala de Plata
1551	La Cueva del Llanto
1567	Sosiego del Valor
1588	Isla Yojamba
1683	Puesto Juncobruma
1685	Fuerte Cenarion
1687	Campamento Crepúsculo
1688	Punta de Corzocelada
1689	Paseo Crepúsculo
1690	Guarida de Ortell
1694	Campamento Barbabronce
1702	Los Dominios de Ivar
1703	Campo de Valgan
1749	Torre de la Muralla del Este
1756	Torre del Bosque de la Peste
1763	Torre del Paso del Norte
1770	Torre de la Corona
7713	Altar del loa de la sangre
7714	Altar del loa de la sangre
7715	Altar del loa de la sangre
7716	Altar del loa de la sangre
7717	Altar del loa de la sangre
]],
    },
    ptBR = {
        flights = [[
1	Abadia de Vila Norte
2	Ventobravo, Elwynn
4	Morro da Sentinela, Cerro Oeste
5	Vila Plácida, Montanhas Cristarrubra
6	Altaforja, Dun Morogh
7	Porto de Menethil, Pantanal
8	Thelsamar, Loch Modan
9	Angra do Butim, Selva do Espinhaço
10	O Sepulcro, Floresta de Pinhaprata
11	Cidade Baixa, Tirisfal
12	Vila Sombria, Floresta do Crepúsculo
13	Serraria Tarren, Eira dos Montes
14	Costa Sul, Eira dos Montes
15	Terras Pestilentas Orientais
16	Ponta do Refúgio, Arathi
17	Ruína do Martelo, Arathi
18	Angra do Butim, Selva do Espinhaço
19	Angra do Butim, Selva do Espinhaço
20	Grom'gol, Selva do Espinhaço
21	Karrath, Ermos
22	Penhasco do Trovão, Mulgore
23	Orgrimmar, Durotar
24	Genérico, Alvo mundial para Rotas de Zepelim
25	Encruzilhada, Sertões
26	Auberdine, Costa Negra
27	Vila de Rut'theran, Teldrassil
28	Astranaar, Vale Gris
29	Retiro Rocha do Sol, Cordilheira das Torres de Pedra
30	Aldeia Vento Livre, Mil Agulhas
31	Thalanaar, Feralas
32	Theramore, Pântano Vadeoso
33	Morro das Torres de Pedra, Cordilheira das Torres de Pedra
34	Transporte, Angra do Butim - Vila Catraca
35	Transporte, Zepelins de Orgrimmar
36	Genérico, Alvo mundial
37	Posto do Nijel, Desolação
38	Aldeia Pescassombra, Desolação
39	Geringontzan, Tanaris
40	Geringontzan, Tanaris
41	Plumaluna, Feralas
42	Aldeia Mojache, Feralas
43	Ninho da Águia, Terras Agrestes
44	Valormok, Azshara
45	Bastilha de Etergarde, Barreira do Inferno
46	Balsa da Costa Sul, Eira dos Montes
47	Transporte, Grom'gol - Orgrimmar
48	Posto Peçonha, Selva Maleva
49	Clareira da Lua
50	Transporte, Navios de Menethil
51	Transporte, Rut'theran - Auberdine
52	Visteterna, Hibérnia
53	Visteterna, Hibérnia
54	Transporte, Plumaluna - Feralas
55	Aldeia Muralha Verde, Pântano Vadeoso
56	Pedregal, Pântano das Mágoas
57	Colônia de Pescadores, Teldrassil
58	Assentamento Zoram'gar, Vale Gris
61	Posto Machadada, Vale Gris
62	Refúgio Noturno, Clareira da Lua
63	Refúgio Noturno, Clareira da Lua
64	Campo Talrendis, Azshara
65	Clareira da Galhaça, Selva Maleva
66	Acampamento Ventogelante, Terras Pestilentas Ocidentais
67	Capela Esperança da Luz, Terras Pestilentas Orientais
68	Capela Esperança da Luz, Terras Pestilentas Orientais
69	Clareira da Lua
70	Monte Candente, Estepes Ardentes
71	Vigia de Morgan, Estepes Ardentes
72	Forte Cenariano, Silithus
73	Forte Cenariano, Silithus
74	Posto de Tório, Garganta Abrasadora
75	Posto de Tório, Garganta Abrasadora
76	Aldeia Revatusco, Terras Agrestes
77	Acampamento Taurajo, Sertões
78	Naxxramas
79	Refúgio do Marshal, Cratera Un'Goro
80	Vila Catraca, Sertões
84	Torre do Bosque Pestilento, Terras Pestilentas Orientais
85	Torre do Passo Norte, Terras Pestilentas Orientais
86	Torre da Muralha Leste, Terras Pestilentas Orientais
87	Torre da Coroa, Terras Pestilentas Orientais
559	Pico da Eternidade, Monte Hyjal
3203	Rog'mar, Sendas do Rio
3205	Costa Marcha-maré, Dun Morogh
3242	Contraforte Maculado, Monte Hyjal
3274	Porto Detonapavio, Sendas do Rio
3275	Porto Detonapavio, Sendas do Rio
3276	Bastilha de Ermoforte, Sendas do Rio
]],
        towns = [[
1	Sidermar
2	Montalvo
3	Vila Sombria
4	Plangemortis
5	Dun Algaz
6	Dun Modr
7	Vila d'Ouro
8	Altaforja
9	Kharanos
10	Vila Plácida
11	Porto de Menethil
12	Arroio da Lua
13	Abadia de Vila Norte
14	Monte Corvo
15	Morro da Sentinela
16	Ventobravo
17	O Sepulcro
18	Cidade Baixa
19	Thelsamar
22	Costa Sul
23	Serraria Tarren
24	Ponta do Refúgio
25	Ruína do Martelo
26	Karrath
27	Fortaleza Angor
28	Aldeia Casco Sangrento
29	Penhasco do Trovão
30	Aldeia Narache
31	Monte Navalha
32	O Covil
33	Orgrimmar
34	Aldeia Sen'jin
35	A Encruzilhada
36	Aldrassil
37	Dolanaar
38	Darnassus
39	Vila Catraca
40	Angra do Butim
41	Acampamento Grom'gol
42	Astranaar
44	Morro das Torres de Pedra
45	Thalanaar
46	Aldeia Vento Livre
327	Garganta Seca
701	Retiro Rocha do Sol
707	Templo de Zin-Malor
708	Ninho de Hetaera
709	Tumba de Uther
710	Scolomântia
767	Posto Confinalvo
788	Pedregal
789	Geringontzan
790	Aldeia Mojache
791	Ilha Theramore
792	Ninho da Águia
794	Visteterna
795	Aldeia Pescassombra
796	Domínio de Plumaluna
798	Auberdine
799	Posto do Nijel
907	Aldrassil
908	Caverna Fionumbra
909	Pedra Vil
911	Gruta de Ban'ethil
912	A Fenda
913	Garganta do Vento Cortante
929	Fazenda Tor'kren
947	Garagem do Gradaço
948	Complexo de Bandaferro
949	Mina da Serra do Eco
950	Vinhedos dos Madruga
951	Fazenda Campedra
954	Vinhedos de Vila Norte
955	Torre de Ilgalar
956	Rocha dos Laceradores
1007	Covil dos Espíritos
1008	Cavernas Retibanas
1010	Posto Avançado Punho de Pedra
1011	Complexo Grosh'gok
1012	Caverna Pantanal dos Cervos
1013	Templo de Atal'Hakkar
1014	Torre de Arathor
1015	Bastilha Martelo Feroz
1016	Vale Teia da Noite
1017	Túnel Terrorteia
1018	Engenho Assombrado
1027	Uldaman
1028	Gruta Arrota-pó
1029	Guarnição da Ribeira d'Oeste
1030	Mina de Jaspe
1031	Pontal de Janeiro
1032	Estação Algaz
1033	Grim Batol
1047	Acidente da Mina
1048	Antro dos Bosqueneros
1049	Rio Crenado
1050	Quedas de Fontescarpa
1067	Ilha da Peleja
1068	Caverna Ululante
1087	Estalagem Pouso do Umbral
1088	Caverna Névoa Negra
1089	Torre Norte
1090	Charneca Azul
1091	Posto Perdido
1092	Enseada da Fúria das Marés
1093	Ruínas Pedramalho
1094	Covil da Onyxia
1095	Covil de Ardeluta
1096	Antro do Dinossangue
1097	Pontal de Vigília
1098	Casarão do Pantanal Iluminado
1104	Refúgio do Marshal
1105	Pedra do Limo
1106	Praia das Sete Ondas
1107	Uldum
1108	Pináculo da Nuvem Negra
1109	Covil Plumerrante
1110	Circuito da Ilusão
1111	Sítio de Escavação Velhomalho
1112	Castelo do Casco Fendido
1113	Gruta Velha
1114	Acampamento Petraferro
1115	Cratera do Furão
1116	Ruínas de Tahonda
1127	Descanso de Rolando
1128	Refúgio dos Mendigos
1147	Covil do Bolgan
1148	Maraudon
1149	Entreposto do Espírito que Anda
1150	Acampamento do Rabiscafuso
1151	Vale dos Ossos
1168	Bastilha Cortifúria
1169	Ruínas de Solarsal
1171	Acampamento Arrasado do Crepúsculo
1172	Posto Crepúsculo
1173	Posto Avançado do Crepúsculo
1174	Serra dos Patábua
1175	Pavilhão Lariss
1176	Rocha Coleante
1177	Monte Candente
1187	Covil de Shalzaru
1211	Caverna do Barbescama
1212	Domínio dos Presamatos
1213	As Ruínas de Kel'Theril
1214	Dun Mandarr
1215	Campo Talrendis
1216	Sacrário de Rethress
1217	Antro Lunorror
1218	Domínio dos Presamatos
1219	Caverna Ferrárbol
1220	Posto Peçonha
1227	Desfiladeiro Sishir
1228	Lago do Rochedo
1229	Mina Cortavento
1230	Túnel Garracava
1231	Retiro do Gadanho
1232	Ruínas de Ordil'Aran
1233	Refúgio de Bathran
1234	Assentamento Zoram'gar
1235	Rio Felfarren
1237	Xavian
1238	Cantilenda
1239	Cânion do Demônio Caído
1240	Posto Avançado Asa de Prata
1241	O Retiro de Dor'Danil
1242	Refúgio Brisaprata
1243	Aldeia Pataverde
1244	Aldeia Dente Sangrento
1245	Túnel Garracava
1246	Santuário de Remulos
1247	Refúgio Noturno
1248	Templos de Tempesfúria
1268	Campo de Trabalho Brado Guerreiro
1287	Acampamento de Ariden
1288	Garganta do Vento Morto
1289	Garganta Adormecida
1307	Acampamento Ventogelante
1469	Acampamento Taurajo
1471	Posto Machadada
1472	Pilar Enxameante
1473	Ossos de Grakkarond
1475	Covil dos Patábua
1507	Aldeia Revatusco
1508	Posto de Tório
1512	Campo-base de Mor'shan
1513	Bosque Asa de Prata
1551	Caverna das Lágrimas
1567	Repouso dos Valorosos
1588	Ilha Yojamba
1683	Posto Brumalga
1685	Forte Cenariano
1687	Acampamento do Crepúsculo
1688	Posto Guenelmo
1689	Passeio do Crepúsculo
1690	Esconderijo de Ortell
1694	Acampamento Barbabronze
1702	Plantação do Ivar
1703	Sítio do Valgan
1749	Torre da Muralha Leste
1756	Torre do Bosque Pestilento
1763	Torre do Passo Norte
1770	Torre da Coroa
7713	Altar do Loa Sangrento
7714	Altar do Loa Sangrento
7715	Altar do Loa Sangrento
7716	Altar do Loa Sangrento
7717	Altar do Loa Sangrento
]],
    },
    ruRU = {
        flights = [[
1	Аббатство Североземья
2	Штормград, Элвин
4	Сторожевой холм, Западный Край
5	Приозерье, Красногорье
6	Стальгорн, Дун Морог
7	Гавань Менетилов, Болотина
8	Телcамар, озеро Лок Модан
9	Пиратская бухта, Тернистая долина
10	Гробница, Серебряный бор
11	Подгород, Тирисфаль
12	Темнолесье, Сумеречный лес
13	Мельница Таррен, Хилсбрад
14	Южнобережье, Хилсбрад
15	Восточные Чумные земли
16	Опорный пункт, Арати
17	Павший Молот, Арати
18	Пиратская бухта, Тернистая долина
19	Пиратская бухта, Тернистая долина
20	Гром'гол, Тернистая долина
21	Каргат, Бесплодные земли
22	Громовой Утес, Мулгор
23	Оргриммар, Дуротар
24	Стандартный, мир, цель для маршрутов дирижаблей
25	Перекресток, Степи
26	Аубердин, Темный Берег
27	Деревня Рут'теран, Тельдрассил
28	Астранаар, Ясеневый лес
29	Приют у Солнечного Камня, Когтистые горы
30	Застава Вольный Ветер, Тысяча Игл
31	Таланаар, Фералас
32	Терамор, Пылевые топи
33	Пик Каменного Когтя, Когтистые горы
34	Транспорт, Пиратская Бухта
35	Транспорт, Оргриммар, дирижабли
36	Стандартный, мир, цель
37	Высота Найджела, Пустоши
38	Деревня Ночных Охотников, Пустоши
39	Прибамбасск, Танарис
40	Прибамбасск, Танарис
41	Лунное Перо, Фералас
42	Лагерь Мохаче, Фералас
43	Заоблачный пик, Внутренние земли
44	Храбростан, Азшара
45	Крепость Стражей Пустоты, Выжженные земли
46	Паром, Южнобережье, Хилсбрад
47	Транспорт, Гром'гол - Оргриммар
48	Застава Отравленной Крови, Оскверненный лес
49	Лунная поляна
50	Транспорт, гавань Менетил, корабли
51	Транспорт, Рут'теран - Аубердин
52	Круговзор, Зимние Ключи
53	Круговзор, Зимние Ключи
54	Транспорт, крепость Оперенной Луны - Фералас
55	Деревня Гиблотопь, Пылевые топи
56	Каменор, Болото Печали
57	Рыбацкий поселок, Тельдрассил
58	Форт Зорам'гар, Ясеневый лес
61	Застава Расщепленного Древа, Ясеневый лес
62	Ночная Гавань, Лунная поляна
63	Ночная Гавань, Лунная поляна
64	Застава Талрендис, Азшара
65	Поляна Когтистых Ветвей, Оскверненный лес
66	Лагерь Промозглого Ветра, Западные Чумные земли
67	Часовня Последней Надежды, Восточные Чумные земли
68	Часовня Последней Надежды, Восточные Чумные земли
69	Лунная поляна
70	Пламенеющий Стяг, Пылающие степи
71	Дозор Моргана, Пылающие степи
72	Крепость Кенария, Силитус
73	Крепость Кенария, Силитус
74	Лагерь Братства Тория, Тлеющее ущелье
75	Лагерь Братства Тория, Тлеющее ущелье
76	Деревня Сломанного Клыка, Внутренние земли
77	Лагерь Таурахо, Степи
78	Наксрамас
79	Укрытие Маршалла, Кратер Ун'Горо
80	Кабестан, Степи
84	Башня Проклятого леса, Восточные Чумные земли
85	Башня Северного перевалa, Восточные Чумные земли
86	Восточная башня, Восточные Чумные земли
87	Башня королевской стражи, Восточные Чумные земли
559	Вершина Вечности, гора Хиджал
3203	Рог'мар, Лесоречье
3205	Волнолязг, Дун Морог
3242	Оскверненные предгорья, Гора Хиджал
3274	Пороховой порт, Лесоречье
3275	Пороховой порт, Лесоречье
3276	Крепость Фархолд, Лесоречье
]],
        towns = [[
1	Старая Наковальня
2	Брилл
3	Темнолесье
4	Могильник
5	Дун Альгаз
6	Дун Модр
7	Златоземье
8	Стальгорн
9	Каранос
10	Приозерье
11	Гавань Менетилов
12	Луноречье
13	Аббатство Североземья
14	Вороний Холм
15	Сторожевой холм
16	Штормград
17	Гробница
18	Подгород
19	Телсамар
22	Южнобережье
23	Мельница Таррен
24	Опорный пункт
25	Павший Молот
26	Каргат
27	Крепость Ангор
28	Деревня Кровавого Копыта
29	Громовой Утес
30	Лагерь Нараче
31	Колючий Холм
32	Логово
33	Оргриммар
34	Деревня Сен'джин
35	Перекресток
36	Альдрассил
37	Доланаар
38	Дарнасс
39	Кабестан
40	Пиратская бухта
41	Лагерь Гром'гол
42	Астранаар
44	Пик Каменного Когтя
45	Таланаар
46	Застава Вольного Ветра
327	Теснина Сухоусов
701	Приют у Солнечного Камня
707	Храм Зин-Малор
708	Гнездо Хетайры
709	Гробница Утера
710	Некроситет
767	Застава Белого Плеса
788	Каменор
789	Прибамбасск
790	Лагерь Мохаче
791	Остров Терамор
792	Заоблачный Пик
794	Круговзор
795	Деревня Ночных Охотников
796	Крепость Оперенной Луны
798	Аубердин
799	Высота Найджела
907	Альдрассил
908	Паучье логово
909	Пещера Бесов
911	Обитель Бен'этиль
912	Расселина
913	Каньон Колючего Ветра
929	Ферма Тор'кренов
947	Поселок Сталежара
948	Мастерская Сталекрута
949	Рудник Горного Эха
950	Виноградники Маклура
951	Ферма Стоунфилдов
954	Виноградники Североземья
955	Башня Илгалара
956	Скала Ренда
1007	Пещера Духов
1008	Пещеры Ретбана
1010	Аванпост Тяжелого Кулака
1011	Поселок Грош'гок
1012	Пещера у Вязкой топи
1013	Храм Атал'Хаккара
1014	Башня Аратора
1015	Крепость Громового Молота
1016	Паучья низина
1017	Туннель Ужаса
1018	Мельница Бровача
1027	Ульдаман
1028	Грот Гнилобрюхих
1029	Гарнизон у Западного ручья
1030	Яшмовая шахта
1031	Остров Жанейро
1032	Станция Альгаз
1033	Грим Батол
1047	Рудник Торговой компании
1048	Берлога в Чернолесье
1049	Петляющая река
1050	Водопад Скалистый
1067	Остров Битв
1068	Пещеры Стенаний
1087	Таверна "Последний привал"
1088	Мглистая пещера
1089	Северная башня
1090	Синяя топь
1091	Разрушенная башня
1092	Залив Яростных Волн
1093	Руины Деревни Каменного Молота
1094	Логово Ониксии
1095	Логово Огнебора
1096	Логово Кровавой Топи
1097	Сторожевой пост
1098	Сторожка "Болотный огонек"
1104	Укрытие Маршалла
1105	Пещера Лишайников
1106	Берег Морского Бродяги
1107	Ульдум
1108	Пик Темного Облака
1109	Логово Легкоперых
1110	Виражи на Миражах
1111	Карьер Ржавого Молота
1112	Оплот Треснувшего Копыта
1113	Угол Семи Ветров
1114	Лагерь Железного Камня
1115	Кратер Криворука
1116	Руины Тахонды
1127	Погибель Роланда
1128	Приют Бродяги
1147	Пещера Болгана
1148	Мародон
1149	Застава Скитающихся Духов
1150	Лагерь Заржавня
1151	Долина Костей
1168	Пещера Бешеного оврага
1169	Руины Соларсаля
1171	Разоренный Сумеречный лагерь
1172	Сумеречная застава
1173	Сумеречный форт
1174	Холмы Древолапов
1175	Павильон Лорисс
1176	Скользкая скала
1177	Пламенеющий Стяг
1187	Убежище Шалзару
1211	Пещера Чешуеборода
1212	Крепость Древобрюхов
1213	Руины Кел'Терила
1214	Дун Мандарр
1215	Застава Талрендис
1216	Святилище Ретресса
1217	Обитель Лунного Ужаса
1218	Крепость Древобрюхов
1219	Пещера Железнолесья
1220	Застава Отравленной Крови
1227	Сиширский каньон
1228	Скалистое озеро
1229	Рудник Ветрорезов
1230	Туннель Когтя
1231	Пещера Когтей
1232	Руины Ордил'Арана
1233	Убежище Батрана
1234	Форт Зорам'гар
1235	Река Фалфаррен
1237	Ксавиан
1238	Лесная Песнь
1239	Каньон Гибели Демона
1240	Аванпост Среброкрылых
1241	Обитель Дор'Данил
1242	Приют Серебряного Ветра
1243	Деревня Зеленой Лапы
1244	Лагерь Кровавого Клыка
1245	Туннель Когтя
1246	Святилище Ремулоса
1247	Ночная Гавань
1248	Кельи Малфуриона
1268	Рабочий лагерь Песни Войны
1287	Лагерь Аридена
1288	Овраг Мертвого Ветра
1289	Спящая теснина
1307	Лагерь Промозглого Ветра
1469	Лагерь Таурахо
1471	Застава Расщепленного Дерева
1472	Роящаяся вершина
1473	Кости Граккаронда
1475	Логово Древолапов
1507	Деревня Сломанного Клыка
1508	Лагерь Братства Тория
1512	Лагерь Мор'шан
1513	Роща Среброкрылых
1551	Грот Слез
1567	Погост Отважных
1588	Остров Йоджамба
1683	Тростниковая застава
1685	Крепость Кенария
1687	Сумеречный лагерь
1688	Лагерь Оленьего Шлема
1689	Сумеречная пещера
1690	Укрытие Ортелла
1694	Лагерь Бронзоборода
1702	Делянка Ивара
1703	Поле Валгана
1749	Восточная башня
1756	Башня Проклятого леса
1763	Башня Северного перевала
1770	Башня королевской стражи
7713	Алтарь лоа крови
7714	Алтарь лоа крови
7715	Алтарь лоа крови
7716	Алтарь лоа крови
7717	Алтарь лоа крови
]],
    },
    zhCN = {
        flights = [[
1	北郡修道院
2	暴风城，艾尔文森林
4	哨兵岭，西部荒野
5	湖畔镇，赤脊山
6	铁炉堡，丹莫罗
7	米奈希尔港，湿地
8	塞尔萨玛，洛克莫丹
9	藏宝海湾，荆棘谷
10	瑟伯切尔，银松森林
11	幽暗城，提瑞斯法林地
12	夜色镇，暮色森林
13	塔伦米尔，希尔斯布莱德
14	南海镇，希尔斯布莱德
15	东瘟疫之地
16	避难谷地，阿拉希高地
17	落锤镇，阿拉希高地
18	藏宝海湾，荆棘谷
19	藏宝海湾，荆棘谷
20	格罗姆高，荆棘谷
21	卡加斯，荒芜之地
22	雷霆崖，莫高雷
23	奥格瑞玛，杜隆塔尔
24	Generic, World target for Zeppelin Paths
25	十字路口，贫瘠之地
26	奥伯丁，黑海岸
27	鲁瑟兰村，泰达希尔
28	阿斯特兰纳，灰谷
29	烈日石居，石爪山
30	乱风岗 ，千针石林
31	萨兰纳尔，千针石林
32	塞拉摩，尘泥沼泽
33	石爪峰，石爪山
34	棘齿城到藏宝海湾的船只
35	奥格瑞玛的飞艇
36	Generic, World target
37	尼耶尔前哨站，凄凉之地
38	葬影村，凄凉之地
39	加基森，塔纳利斯
40	加基森，塔纳利斯
41	羽月要塞，菲拉斯
42	莫沙彻营地，菲拉斯
43	鹰巢山，辛特兰
44	瓦罗莫克，艾萨拉
45	守望堡，诅咒之地
46	南海镇渡口，希尔斯布莱德
47	格罗姆高到奥格瑞玛的飞艇
48	血毒河，费伍德森林
49	月光林地
50	米奈希尔的船只
51	鲁瑟兰到奥伯丁的船只
52	永望镇，冬泉谷
53	永望镇，冬泉谷
54	羽月要塞 - 菲拉斯
55	蕨墙村，尘泥沼泽
56	斯通纳德，悲伤沼泽
57	钓鱼村，泰达希尔
58	佐拉姆加前哨站，灰谷
61	碎木岗哨，灰谷
62	永夜港，月光林地
63	永夜港，月光林地
64	塔伦迪斯营地，艾萨拉
65	刺枝林地，费伍德森林
66	冰风岗，西瘟疫之地
67	圣光之愿礼拜堂，东瘟疫之地
68	圣光之愿礼拜堂，东瘟疫之地
69	月光林地
70	烈焰峰，燃烧平原
71	摩根的岗哨，燃烧平原
72	塞纳里奥要塞，希利苏斯
73	塞纳里奥要塞，希利苏斯
74	瑟银哨塔，灼热峡谷
75	瑟银哨塔，灼热峡谷
76	恶齿村，辛特兰
77	陶拉祖营地，贫瘠之地
78	纳克萨玛斯
79	马绍尔营地，安戈洛环形山
80	棘齿城，贫瘠之地
84	病木林哨塔，东瘟疫之地
85	北地哨塔，东瘟疫之地
86	东墙哨塔，东瘟疫之地
87	皇冠哨塔，东瘟疫之地
559	永恒之巅，海加尔山
3203	洛格玛，河林
3205	潮齿海岸，丹莫罗
3242	污染山麓，海加尔山
3274	爆破引线港，河林
3275	爆破引线港，河林
3276	法霍德要塞，河林
]],
        towns = [[
1	安威玛尔
2	布瑞尔
3	夜色镇
4	丧钟镇
5	丹奥加兹
6	丹莫德
7	闪金镇
8	铁炉堡
9	卡拉诺斯
10	湖畔镇
11	米奈希尔港
12	月溪镇
13	北郡修道院
14	乌鸦岭
15	哨兵岭
16	暴风城
17	瑟伯切尔
18	幽暗城
19	塞尔萨玛
22	南海镇
23	塔伦米尔
24	避难谷地
25	落锤镇
26	卡加斯
27	苦痛堡垒
28	血蹄村
29	雷霆崖
30	纳拉其营地
31	剃刀岭
32	大兽穴
33	奥格瑞玛
34	森金村
35	十字路口
36	奥达希尔
37	多兰纳尔
38	达纳苏斯
39	棘齿城
40	藏宝海湾
41	格罗姆高营地
42	阿斯特兰纳
44	石爪峰
45	萨兰纳尔
46	乱风岗
327	枯须峡谷
701	烈日石居
707	辛玛洛神殿
708	赫塔拉的巢穴
709	乌瑟尔之墓
710	通灵学院
767	白沙岗哨
788	斯通纳德
789	加基森
790	莫沙彻营地
791	塞拉摩岛
792	鹰巢山
794	永望镇
795	葬影村
796	羽月要塞
798	奥伯丁
799	尼耶尔前哨站
907	奥达希尔
908	黑丝洞
909	地狱石
911	班奈希尔兽穴
912	大断崖
913	烈风峡谷
929	托克雷农场
947	钢架补给站
948	铁环营地
949	回音山矿洞
950	马科伦农场
951	斯通菲尔德农场
954	北郡农场
955	伊尔加拉之塔
956	撕裂者之石
1007	灵魂之穴
1008	瑞斯班洞穴
1010	石拳前哨
1011	格罗高克营地
1012	雄鹿沼泽洞穴
1013	阿塔哈卡神庙
1014	阿拉索之塔
1015	蛮锤城堡
1016	夜行蜘蛛洞穴
1017	恶蛛隧道
1018	布洛米尔
1027	奥达曼
1028	火山洞穴
1029	西泉要塞
1030	玉石矿洞
1031	加尼罗哨站
1032	奥加兹岗哨
1033	格瑞姆巴托
1047	风险投资公司矿洞
1048	黑木洞穴
1049	急弯河
1050	峭壁之泉
1067	勇士岛
1068	哀嚎洞穴
1087	树荫旅店
1088	黑雾洞穴
1089	北点哨塔
1090	蓝色沼泽
1091	废弃哨塔
1092	狂潮湾
1093	石槌废墟
1094	奥妮克希亚的巢穴
1095	埃博斯塔夫的巢穴
1096	鲜血沼泽墓穴
1097	警戒哨岗
1098	水光庄园
1104	马绍尔营地
1105	蘑菇石
1106	破浪海滩
1107	奥丹姆
1108	黑云峰
1109	飞羽洞穴
1110	沙漠赛道
1111	锈锤挖掘场
1112	裂蹄堡
1113	老屋
1114	铁石营地
1115	维吉尔之坑
1116	塔霍达废墟
1127	罗兰之墓
1128	乞丐鬼屋
1147	波尔甘的洞穴
1148	玛拉顿
1149	幽灵岗哨
1150	瑟卡布斯库的营地
1151	白骨之谷
1168	怒痕堡
1169	索兰萨尔废墟
1171	暮光营地废墟
1172	暮光岗哨
1173	暮光前哨站
1174	木爪岭
1175	拉瑞斯小亭
1176	滑石
1177	烈焰峰
1187	沙尔扎鲁的巢穴
1211	鳞须海龟洞穴
1212	木喉要塞
1213	凯斯利尔废墟
1214	丹曼达尔
1215	塔伦迪斯营地
1216	雷瑟斯圣所
1217	惨月洞穴
1218	木喉要塞
1219	铁木山洞
1220	血毒岗哨
1227	希塞尔山谷
1228	峭壁湖
1229	狂风矿洞
1230	石爪小径
1231	猛禽洞穴
1232	奥迪拉兰废墟
1233	巴斯兰鬼屋
1234	佐拉姆加前哨站
1235	弗伦河
1237	萨维亚
1238	林歌神殿
1239	屠魔峡谷
1240	银翼哨站
1241	朵丹尼尔兽穴
1242	银风避难所
1243	绿爪村
1244	血牙营地
1245	石爪小径
1246	雷姆洛斯神殿
1247	永夜港
1248	怒风兽穴
1268	战歌劳工营地
1287	埃瑞丁营地
1288	逆风谷
1289	沉睡峡谷
1307	寒风营地
1469	陶拉祖营地
1471	碎木岗哨
1472	虫群之柱
1473	格拉卡隆之骨
1475	木爪洞穴
1507	恶齿村
1508	瑟银哨塔
1512	莫尔杉营地
1513	银翼树林
1551	哭泣洞穴
1567	勇士之墓
1588	尤亚姆巴岛
1683	芦苇哨岗
1685	塞纳里奥要塞
1687	暮光营地
1688	鹿盔岗哨
1689	暮光小径
1690	奥泰尔隐居处
1694	铜须营地
1702	伊瓦农场
1703	瓦尔甘农场
1749	东墙哨塔
1756	病木林哨塔
1763	北地哨塔
1770	皇冠哨塔
7713	血神祭坛
7714	血神祭坛
7715	血神祭坛
7716	血神祭坛
7717	血神祭坛
]],
    },
    zhTW = {
        flights = [[
1	北郡修道院
2	暴風城，艾爾文森林
4	哨兵嶺，西部荒野
5	湖畔鎮，赤脊山
6	鐵爐堡，丹莫洛
7	米奈希爾港，濕地
8	塞爾薩瑪，洛克莫丹
9	藏寶海灣，荊棘谷
10	瑟伯切爾，銀松森林
11	幽暗城，提里斯法林地
12	夜色鎮，暮色森林
13	塔倫米爾，希爾斯布萊德
14	南海鎮，希爾斯布萊德
15	東瘟疫之地
16	避難谷地，阿拉希高地
17	落錘鎮，阿拉希高地
18	藏寶海灣，荊棘谷
19	藏寶海灣，荊棘谷
20	格羅姆高，荊棘谷
21	卡加斯，荒蕪之地
22	雷霆崖，莫高雷
23	奧格瑪，杜洛塔
24	Generic, World target for Zeppelin Paths
25	十字路口，貧瘠之地
26	奧伯丁，黑海岸
27	魯瑟蘭村，泰達希爾
28	阿斯特蘭納，梣谷
29	烈日石居，石爪山
30	亂風崗 ，千針石林
31	薩蘭納爾，千針石林
32	塞拉摩，塵泥沼澤
33	石爪峰，石爪山
34	傳送，藏寶海灣 - 棘齒城
35	傳送，奧格瑪飛艇
36	Generic, World target
37	尼耶爾前哨站，淒涼之地
38	葬影村，淒涼之地
39	加基森，塔納利斯
40	加基森，塔納利斯
41	羽月要塞，菲拉斯
42	莫沙徹營地，菲拉斯
43	鷹巢山，辛特蘭
44	瓦羅莫克，艾薩拉
45	守望堡，詛咒之地
46	南海鎮渡口，希爾斯布萊德
47	傳送，格羅姆 - 奧格瑪
48	血毒崗哨，費伍德森林
49	月光林地
50	傳送，米奈希爾船隻
51	傳送，魯瑟蘭 - 奧伯丁
52	永望鎮，冬泉谷
53	永望鎮，冬泉谷
54	傳送，羽月要塞 - 菲拉斯
55	蕨牆村，塵泥沼澤
56	斯通納德，悲傷沼澤
57	釣魚村，泰達希爾
58	左拉姆加前哨站，梣谷
61	碎木崗哨，梣谷
62	永夜港，月光林地
63	永夜港，月光林地
64	塔倫迪斯營地，艾薩拉
65	刺枝林地，費伍德森林
66	冰風營地，西瘟疫之地
67	聖光之願禮拜堂，東瘟疫之地
68	聖光之願禮拜堂，東瘟疫之地
69	月光林地
70	烈焰峰，燃燒平原
71	摩根的崗哨，燃燒平原
72	塞納里奧城堡，希利蘇斯
73	塞納里奧城堡，希利蘇斯
74	瑟銀哨塔，灼熱峽谷
75	瑟銀哨塔，灼熱峽谷
76	惡齒村，辛特蘭
77	陶拉祖營地，貧瘠之地
78	納克薩瑪斯
79	馬紹爾營地，安戈洛環形山
80	棘齒城，貧瘠之地
84	病木林哨塔，東瘟疫之地
85	北地哨塔，東瘟疫之地
86	東牆之塔，東瘟疫之地
87	皇冠哨塔，東瘟疫之地
559	永恆山峰，海加爾山
3203	大河林地，羅格瑪
3205	泰德基爾海岸，丹莫洛
3242	污化丘陵，海加爾山
3274	火線港，大河林地
3275	火線港，大河林地
3276	遠境堡要塞，大河林地
]],
        towns = [[
1	安威瑪
2	布瑞爾
3	夜色鎮
4	喪鐘鎮
5	丹奧加茲
6	丹莫德
7	閃金鎮
8	鐵爐堡
9	卡拉諾斯
10	湖畔鎮
11	米奈希爾港
12	月溪鎮
13	北郡修道院
14	烏鴉嶺
15	哨兵嶺
16	暴風城
17	瑟伯切爾
18	幽暗城
19	塞爾薩瑪
22	南海鎮
23	塔倫米爾
24	避難谷地
25	落錘鎮
26	卡加斯
27	苦痛堡壘
28	血蹄村
29	雷霆崖
30	納拉其營地
31	剃刀嶺
32	大獸穴
33	奧格瑪
34	森金村
35	十字路口
36	奧達希爾
37	多蘭納爾
38	達納蘇斯
39	棘齒城
40	藏寶海灣
41	格羅姆高營地
42	阿斯特蘭納
44	石爪峰
45	薩蘭納爾
46	亂風崗
327	枯鬚峽谷
701	烈日石居
707	辛瑪洛神殿
708	赫塔拉的巢穴
709	烏瑟之墓
710	通靈學院
767	白沙崗哨
788	斯通納德
789	加基森
790	莫沙徹營地
791	塞拉摩島
792	鷹巢山
794	永望鎮
795	葬影村
796	羽月要塞
798	奧伯丁
799	尼耶爾前哨站
907	奧達希爾
908	影絲洞
909	地獄石
911	班奈希爾獸穴
912	大斷崖
913	烈風峽谷
929	托克雷農場
947	鋼架補給站
948	鐵環營地
949	回音山礦坑
950	馬科倫農場
951	斯通菲爾德農場
954	北郡農場
955	伊爾加拉之塔
956	撕裂者之石
1007	靈魂之穴
1008	瑞斯班洞穴
1010	石拳崗哨
1011	格羅高克營地
1012	雄鹿沼澤洞穴
1013	阿塔哈卡神廟
1014	阿拉索之塔
1015	蠻錘城堡
1016	夜行蜘蛛洞穴
1017	惡蛛隧道
1018	布洛米爾
1027	奧達曼
1028	火山洞穴
1029	西泉要塞
1030	玉石礦坑
1031	加尼祿哨站
1032	奧加茲崗哨
1033	格瑞姆巴托
1047	風險投資公司礦坑
1048	黑木洞穴
1049	急彎河
1050	峭壁之泉
1067	勇士島
1068	哀嚎洞穴
1087	樹蔭旅店
1088	暗霧洞穴
1089	北點哨塔
1090	藍色沼澤
1091	廢棄哨塔
1092	狂潮灣
1093	石槌廢墟
1094	奧妮克希亞的巢穴
1095	艾博斯塔夫的巢穴
1096	鮮血沼澤墓穴
1097	警戒崗哨
1098	水光莊園
1104	馬紹爾營地
1105	蘑菇石
1106	破浪海灘
1107	奧丹姆
1108	暗雲峰
1109	飛羽洞穴
1110	沙漠賽道
1111	鏽錘挖掘場
1112	裂蹄堡
1113	老屋
1114	鐵石營地
1115	維吉爾之坑
1116	塔霍達廢墟
1127	羅蘭之墓
1128	乞丐鬼屋
1147	波爾甘的洞穴
1148	瑪拉頓
1149	鬼旅崗哨
1150	瑟卡布斯庫的營地
1151	白骨之谷
1168	怒痕堡
1169	索蘭薩爾廢墟
1171	暮光營地廢墟
1172	暮光崗哨
1173	暮光前哨站
1174	木爪嶺
1175	拉瑞斯小亭
1176	滑石
1177	烈焰峰
1187	沙爾札魯的巢穴
1211	鱗鬚海龜洞穴
1212	木喉要塞
1213	凱斯利爾廢墟
1214	丹曼達爾
1215	塔倫迪斯營地
1216	雷瑟斯聖所
1217	慘月洞穴
1218	木喉要塞
1219	鐵木山洞
1220	血毒崗哨
1227	希塞爾山谷
1228	峭壁湖
1229	狂風礦坑
1230	石爪小徑
1231	猛禽洞穴
1232	奧迪拉蘭廢墟
1233	巴斯蘭鬼屋
1234	左拉姆加前哨站
1235	弗倫河
1237	薩維亞
1238	林歌神殿
1239	屠魔峽谷
1240	銀翼哨站
1241	朵丹尼爾獸穴
1242	銀風避難所
1243	綠爪村
1244	血牙營地
1245	石爪小徑
1246	雷姆洛斯神殿
1247	永夜港
1248	怒風獸穴
1268	戰歌勞工營地
1287	埃瑞丁營地
1288	逆風谷
1289	沉睡峽谷
1307	冰風營地
1469	陶拉祖營地
1471	碎木崗哨
1472	蟲群之柱
1473	格拉卡隆之骨
1475	木爪洞穴
1507	惡齒村
1508	瑟銀哨塔
1512	莫爾杉營地
1513	銀翼樹林
1551	哭泣洞穴
1567	勇士之墓
1588	尤亞姆巴島
1683	蘆葦崗哨
1685	塞納里奧城堡
1687	暮光營地
1688	鹿盔崗哨
1689	暮光基地
1690	奧泰爾的隱居處
1694	銅鬚營地
1702	伊瓦的地盤
1703	瓦爾甘的田地
1749	東牆之塔
1756	病木林哨塔
1763	北地哨塔
1770	皇冠哨塔
7713	鮮血羅亞祭壇
7714	鮮血羅亞祭壇
7715	鮮血羅亞祭壇
7716	鮮血羅亞祭壇
7717	鮮血羅亞祭壇
]],
    },
    koKR = {
        flights = [[
1	노스샤이어 대성당
2	스톰윈드 (엘윈 숲)
4	감시의 언덕 (서부 몰락지대)
5	레이크샤이어 (붉은마루 산맥)
6	아이언포지 (던 모로)
7	메네실 항구 (저습지)
8	텔사마 (모단 호수)
9	무법항 (가시덤불 골짜기)
10	공동묘지 (은빛소나무 숲)
11	언더시티 (티리스팔 숲)
12	다크샤이어 (그늘숲)
13	타렌 밀농장 (힐스브래드 구릉지)
14	사우스쇼어 (힐스브래드 구릉지)
15	동부 역병지대
16	임시 주둔지 (아라시 고원)
17	해머폴 (아라시 고원)
18	무법항 (가시덤불 골짜기)
19	무법항 (가시덤불 골짜기)
20	그롬골 (가시덤불 골짜기)
21	카르가스 (황야의 땅)
22	썬더 블러프 (멀고어)
23	오그리마 (듀로타)
24	일반 (비행선 경로)
25	크로스로드 (불모의 땅)
26	아우버다인 (어둠의 해안)
27	루테란 마을 (텔드랏실)
28	아스트라나르 (잿빛 골짜기)
29	해바위 야영지 (돌발톱 산맥)
30	높새바람 봉우리 (버섯구름 봉우리)
31	탈라나르 (페랄라스)
32	테라모어 섬 (먼지진흙 습지대)
33	돌발톱 봉우리 (돌발톱 산맥)
34	운송 수단 (무법항 ~ 톱니항)
35	운송 수단 (오그리마 비행선)
36	일반 (세계 대상)
37	나이젤의 야영지 (잊혀진 땅)
38	그늘수렵 마을 (잊혀진 땅)
39	가젯잔 (타나리스)
40	가젯잔 (타나리스)
41	페더문 요새 (페랄라스)
42	모자케 야영지 (페랄라스)
43	맹금의 봉우리 (동부 내륙지)
44	발로르모크 (아즈샤라)
45	네더가드 요새 (저주받은 땅)
46	사우스쇼어 선착장 (힐스브래드 구릉지)
47	운송 수단 (그롬골 ~ 오그리마)
48	피멍울 초소 (악령의 숲)
49	달의 숲
50	운송 수단 (메네실 여객선)
51	운송 수단 (루테란 ~ 아우버다인)
52	눈망루 마을 (여명의 설원)
53	눈망루 마을 (여명의 설원)
54	운송 수단 (페더문 - 페랄라스)
55	담쟁이 마을 (먼지진흙 습지대)
56	스토나드 (슬픔의 늪)
57	고기잡이 마을 (텔드랏실)
58	조람가르 전초기지 (잿빛 골짜기)
61	토막나무 주둔지 (잿빛 골짜기)
62	나이트헤이븐 (달의 숲)
63	나이트헤이븐 (달의 숲)
64	탈렌드리스 초소 (아즈샤라)
65	갈퀴가지 숲 (악령의 숲)
66	서리바람 야영지 (서부 역병지대)
67	희망의 빛 예배당 (동부 역병지대)
68	희망의 빛 예배당 (동부 역병지대)
69	달의 숲
70	화염 마루 (불타는 평원)
71	모건의 망루 (불타는 평원)
72	세나리온 요새 (실리더스)
73	세나리온 요새 (실리더스)
74	토륨 조합 거점 (이글거리는 협곡)
75	토륨 조합 거점 (이글거리는 협곡)
76	레반터스크 마을 (동부 내륙지)
77	타우라조 야영지 (불모의 땅)
78	낙스라마스
79	마샬의 야영지 (운고로 분화구)
80	톱니항 (불모의 땅)
84	역병의 숲 경비탑 (동부 역병지대)
85	북부관문 경비탑 (동부 역병지대)
86	동부방벽 경비탑 (동부 역병지대)
87	산마루 경비탑 (동부 역병지대)
559	영원의 정상 - 하이잘 산
3203	강물터 로그마
3205	타이드기어 해안 - 던 모로
3242	오염된 기슭 - 하이잘 산
3274	화약심지 항구 - 강물터
3275	화약심지 항구 - 강물터
3276	파홀드 성채 - 강물터
]],
        towns = [[
1	앤빌마
2	브릴
3	다크샤이어
4	데스넬
5	던 알가즈
6	던 모드르
7	골드샤이어
8	아이언포지
9	카라노스
10	레이크샤이어
11	메네실 항구
12	문브룩
13	노스샤이어 수도원
14	까마귀 언덕
15	감시의 언덕
16	스톰윈드
17	공동묘지
18	언더시티
19	텔사마
22	사우스쇼어
23	타렌 밀농장
24	임시 주둔지
25	해머폴
26	카르가스
27	고통의 요새
28	블러드후프 마을
29	썬더 블러프
30	나라체 야영지
31	칼바위 언덕
32	동굴 막사
33	오그리마
34	센진 마을
35	크로스로드
36	알드랏실
37	돌라나르
38	다르나서스
39	톱니항
40	무법항
41	그롬골 주둔지
42	아스트라나르
44	돌발톱 봉우리
45	탈라나르
46	높새바람 봉우리
327	마른수염 골짜기
701	해바위 야영지
707	진말로의 신전
708	헤타에라의 손아귀
709	우서 경의 무덤
710	스칼로맨스
767	백사장 야영지
788	스토나드
789	가젯잔
790	모자케 야영지
791	테라모어 섬
792	맹금의 봉우리
794	눈망루 마을
795	그늘수렵 마을
796	페더문 요새
798	아우버다인
799	나이젤의 야영지
907	알드랏실
908	그늘 거미굴
909	악마 바위굴
911	바네실 지하굴
912	바위 동굴
913	칼바람 협곡
929	톨크렌 농장
947	스틸그릴의 정비소
948	아이언밴드 야영지
949	메아리 광산
950	맥클루어 포도밭
951	스톤필드 농장
954	노스샤이어 포도밭
955	일갈라의 탑
956	약탈의 바위굴
1007	정기의 동굴
1008	레스밴 동굴
1010	돌주먹 전초기지
1011	그로쉬고크 주둔지
1012	진흙늪 동굴
1013	아탈학카르 신전
1014	아라소르의 탑
1015	와일드해머 요새
1016	검은그물 거미굴
1017	공포의 거미굴
1018	브라우만 밀농장
1027	울다만
1028	먼지목도리 소굴
1029	서부 주둔지
1030	석영 광산
1031	자네이로 섬
1032	알가즈 주둔지
1033	그림 바톨
1047	투자개발회사 광산
1048	검은나무일족 소굴
1049	성난굽이 강
1050	절벽 폭포
1067	격투의 섬
1068	통곡의 동굴
1087	그늘 쉼터 여관
1088	암흑안개 거미굴
1089	북부 경비탑
1090	푸른늪지
1091	버려진 경비탑
1092	성난파도 만
1093	돌망치일족 폐허
1094	오닉시아의 둥지
1095	엠버스트라이프의 굴
1096	붉은늪지 동굴
1097	감시초소
1098	늪지기 오두막
1104	마샬의 야영지
1105	버섯 바위굴
1106	파도타기 해안
1107	울둠
1108	먹구름 봉우리
1109	하피 동굴
1110	신기루 경주장
1111	녹슨망치 발굴현장
1112	갈래발굽 소굴
1113	비바람 바위굴
1114	강철바위 야영지
1115	위젤의 분화구
1116	타혼다 폐허
1127	롤랜드 광산
1128	부랑자 소굴
1147	볼간의 구덩이
1148	마라우돈
1149	침묵의 초소
1150	스크래블스크류의 야영지
1151	뼈의 골짜기
1168	무쇠설인 소굴
1169	솔라살 폐허
1171	파괴된 황혼의 야영지
1172	황혼의 초소
1173	황혼의 전초기지
1174	덩굴발 언덕
1175	라리스 정자
1176	뱀갈퀴 바위굴
1177	화염 마루
1187	샬자루의 둥지
1211	비늘수염 동굴
1212	나무구렁 요새
1213	켈테릴의 폐허
1214	던 만다르
1215	탈렌드리스 초소
1216	레스리스 성소
1217	공포의 달빛 동굴
1218	나무구렁 요새
1219	강철나무 굴
1220	피멍울 초소
1227	시쉬르 협곡
1228	바위웅덩이 호수
1229	칼바람 광산
1230	돌발톱 토굴길
1231	갈퀴발톱굴
1232	오르딜아란의 폐허
1233	배스랜 서식지
1234	조람가르 전초기지
1235	팔파렌 강
1237	사비안
1238	숲의 노래
1239	악마벼락 협곡
1240	은빛날개 전초기지
1241	도르다닐 지하굴
1242	실바람 산장
1243	푸른발 마을
1244	붉은송곳니 야영지
1245	돌발톱 토굴길
1246	레물로스의 제단
1247	나이트헤이븐
1248	스톰레이지 지하굴
1268	전쟁노래부족 노동기지
1287	아리덴의 야영지
1288	죽음의 협곡
1289	수면의 협곡
1307	서리바람 야영지
1469	타우라조 야영지
1471	토막나무 주둔지
1472	벌레무리 기둥
1473	그락카론드의 무덤
1475	덩굴발일족 소굴
1507	레반터스크 마을
1508	토륨 조합 거점
1512	몰샨 주둔지
1513	은빛날개 숲
1551	진흙탕 동굴
1567	용사의 안식처
1588	요잠바 섬
1683	안개갈대 주둔지
1685	세나리온 요새
1687	황혼의 망치단 주둔지
1688	스테그헬름 거점
1689	황혼의 터
1690	오르텔의 은신처
1694	브론즈비어드 야영지
1702	이바르 호박밭
1703	발간 농장
1749	동부방벽 경비탑
1756	역병의 숲 경비탑
1763	북부관문 경비탑
1770	산마루 경비탑
7713	피의 로아의 제단
7714	피의 로아의 제단
7715	피의 로아의 제단
7716	피의 로아의 제단
7717	피의 로아의 제단
]],
    },
}
local locale = GetLocale and GetLocale() or "enUS"
D.client.names = names[locale] or names.enUS
D.client.fallbackNames = names.enUS
